'use strict';
const DATA=window.EMC_DATA;
const $=id=>document.getElementById(id), COLORS=['#b06a16','#2b77cb','#16826c'];
const CASES=[
 {names:['e_near','e_far','e_low'],labels:['A · 가깝게','B · 멀리 떼기','C · 귀환면 가까이'],sub:['간격 4 mm','간격 16 mm','높이 4 mm'],title:'나란한 두 배선, 무엇을 바꾸면 덜 섞일까?',prompt:'먼저 간격을 늘려 보고, 다음에는 두 배선을 귀환면에 가깝게 내려 보자.',measure:'피해 배선 끝에 생긴 전압',norm:'발생원 배선 끝 전압을 1 V RMS로 맞춘 값',unit:'mV',defaultF:100,
 principleTitle:'거리와 귀환면을 함께 본다',principle:'전압이 변하는 도체는 주변 도체와 정전용량으로 결합한다. 피해 회로가 높은 임피던스이면 작은 결합 전류도 큰 전압이 된다. 여기서는 양쪽 회로의 끝 저항을 각각 1 kΩ으로 두었다.',source:'https://learnemc.com/electric-field-coupling',
 sensorTitle:'벅 옆의 가는 신호선',sensor:'스위칭 노드와 센서·리셋 배선이 나란한 구간을 찾는다. 선 사이 거리뿐 아니라 각 선에서 귀환면까지의 높이, 피해 입력의 실제 임피던스를 함께 남긴다.',
 scopeTitle:'회로 전체보다 가까운 두 도체',scope:'배선이 관심 파장에 비해 짧고 전기장 결합이 주된 후보라면, 도체 두 개·귀환면·종단부터 시작할 수 있다. 주변 금속이나 실제 입력 임피던스를 바꿨을 때 결론이 달라지면 그 요소를 추가한다.',
 insight:'<b>“몇 mm 떼면 안전”으로 외우지 말자.</b> 간격 s / 귀환면 높이 h / 피해 임피던스가 함께 결합을 정한다.',
 model:'길이 80 mm, 폭 2 mm의 PEC 배선 두 개. A: h=12, s=4 mm / B: h=12, s=16 mm / C: h=4, s=4 mm. 각 배선의 양 끝은 각각 1 kΩ으로 귀환면에 연결. 발생원 왼쪽에서 여기하고 오른쪽의 실제 전압으로 정규화한다.',
 formula:'V피해 / V발생 ≈ −jωC₂₁ / (2/R + jωC₂₂)',approx:'귀환면의 영상 전하를 이용해 정전용량 행렬을 구했다. 평판 배선을 반지름 w/4의 가는 원형 도선으로 근사한다. 끝부분·포트 주변 장과 전파 지연을 생략하므로 절대값 차이가 남는다. 점선은 결과에 맞춰 보정한 곡선이 아니다.',
 takeaway:'배운 것: 전압 노이즈는 “가까움”과 “받는 쪽 임피던스”를 함께 본다.'},
 {names:['m_large','m_small','m_far'],labels:['A · 높은 루프','B · 낮은 루프','C · 루프 간격 확대'],sub:['높이 12 mm','높이 4 mm','간격 20 mm'],title:'같은 전류라도, 돌아오는 길이 멀면?',prompt:'전류를 같게 두고 왕복 경로의 높이와 두 루프 사이 간격을 바꿔 보자.',measure:'피해 루프 끝의 50 Ω에 생긴 전압',norm:'발생원 배선 끝 전류를 100 mA RMS로 맞춘 값',unit:'mV',defaultF:100,
 principleTitle:'선을 따라갔다면, 돌아오는 길도',principle:'노이즈 전류가 만든 자속 중 피해 루프를 통과하는 부분이 유도 전압을 만든다. 낮은 귀환 경로와 작은 루프는 그 결합을 줄이는 방법이다. 이 실험은 발생원 끝 저항 5 Ω으로 자기장 결합이 두드러지는 조건이다.',source:'https://learnemc.com/magnetic-field-coupling',
 sensorTitle:'모터 전류의 왕복 경로',sensor:'큰 전류가 흐른다는 사실만으로 순위를 정하지 않는다. 빠르게 변하는 전류가 만드는 루프와, 센서·통신 주변의 피해 루프가 얼마나 자속을 공유하는지 본다.',
 scopeTitle:'모터 전체보다 급변 전류 루프',scope:'첫 비교에서는 모터의 기계 형상 대신 관련 전류 루프를 남길 수 있다. 실제 전류 스펙트럼으로 크기를 환산한다. 방향을 바꾸면 공유 자속도 달라지므로 이 평행 루프 결과를 모든 배치에 그대로 적용하지 않는다.',
 insight:'<b>“전류가 큰 선”에서 한 걸음 더.</b> 왕복 경로와 피해 루프를 그려야 자기장 결합을 예상할 수 있다.',
 model:'길이 80 mm, 폭 2 mm. A: h=12, s=8 mm / B: h=4, s=8 mm / C: h=12, s=20 mm. 발생원 양 끝 각각 5 Ω, 피해 배선 양 끝 각각 50 Ω. 그림의 초록 경로는 귀환을 설명하는 대표 경로이며 계산된 전류 분포가 아니다.',
 formula:'M ≈ μ₀ℓ/(4π) · ln(1+4h²/s²)\nV피해 ≈ jωMI · R / (2R+jωL피해)',approx:'귀환면 위 가는 평행 도선의 상호 인덕턴스와 피해 루프의 자기 인덕턴스를 썼다. 유도 기전력 전체가 한 저항에 걸리는 것은 아니므로 양 끝 저항과 루프 인덕턴스로 분압한다.',
 takeaway:'배운 것: di/dt와 두 루프가 공유하는 자속을 함께 본다.'},
 {names:['z_narrow','z_wide'],labels:['A · 좁은 연결','B · 넓은 연결'],sub:['폭 2 mm','폭 12 mm'],title:'같은 GND로 이어져 있는데, 기준이 흔들릴까?',prompt:'같은 길이의 연결을 넓혀 보자. 금속 저항을 0으로 두어도 RF 전압은 생긴다.',measure:'공유 연결의 끝 B와 기준면 사이 전압',norm:'B로 들어가는 총 전류를 100 mA RMS로 맞춘 값',unit:'mV',defaultF:100,
 principleTitle:'회로도의 한 점은 실제로는 경로다',principle:'공유 경로에 전류가 흐르면 그 경로의 임피던스만큼 기준 전위가 달라진다. 여기서는 한쪽이 기준면에 붙은 도체의 입력 임피던스를 구했다. 도체를 PEC로 두어도 루프의 자기 에너지 때문에 RF 임피던스가 남는다.',source:'https://learnemc.com/common-impedance-coupling',
 sensorTitle:'24 V / 0 V와 PHY의 기준',sensor:'24 V 귀환 전류가 어느 커넥터 핀·배선·면을 지나가는지 본다. 그 구간을 PHY나 제어 신호가 기준으로 공유한다면, 칩을 직접 관통하지 않는 전류도 기준 전압을 바꿀 수 있다.',
 scopeTitle:'먼저 두 기준점 사이의 Z',scope:'공유 구간만 작은 모델로 추출해 ΔV=IZ를 구할 수 있다. 여기의 ΔV 전부가 칩 핀에 걸린다고 가정하지 않는다. 다음 단계에서 실제 피해 회로의 연결과 분압을 붙여 전달량을 계산한다.',
 insight:'<b>멀티미터의 “연결됨”은 RF의 “같은 전압”을 보장하지 않는다.</b> 어느 두 점 사이를 기준으로 쓰는지 먼저 표시하자.',
 model:'길이 80 mm, 높이 4 mm. 왼쪽 A에서 PEC 수직 연결로 기준면에 접합하고 오른쪽 B에서 전류를 주입한다. 폭만 2 → 12 mm로 변경. 측정은 B의 수직 포트 전압이며, 상부 경로와 기준면이 만드는 루프의 입력 임피던스다.',
 formula:'Z입력 ≈ jZ₀ tan(βℓ)\n전기적으로 짧을 때: Z입력 ≈ jωL\nΔV = |Z입력| × 0.1 A',approx:'한쪽이 단락된 공기 중 전송선 근사다. Z₀는 폭/높이에서 Hammerstad–Jensen 식으로 계산한다. 실제 구리 저항과 접촉 저항을 뺐으므로 저주파 저항성 전압강하까지 보여 주는 모델은 아니다.',
 takeaway:'배운 것: GND라는 이름보다 공유 전류와 두 기준점 사이 임피던스.'},
 {names:['d_sym','d_asym'],labels:['A · 같은 거리','B · 한쪽에 접근'],sub:['각 선까지 8 mm','4 mm / 12 mm'],title:'두 선이 같이 흔들리면 괜찮을까?',prompt:'두 피해 배선은 그대로 두고, 노이즈 배선만 한쪽으로 옮겨 보자.',measure:'피해 두 선 사이의 차동 노이즈 |V₊ − V₋|',norm:'발생원 배선 끝 전압을 1 V RMS로 맞춘 값',unit:'mV',defaultF:100,
 principleTitle:'두 선 사이의 차이를 읽는다',principle:'같은 외란이 두 선에 같은 크기·위상으로 들어오면 차동 성분은 작다. 주변 도체가 한쪽에 가까워지면 결합이 달라져 차이가 생긴다. 실제 계산에서도 복소 전압을 먼저 빼고 그 크기를 구한다.',source:'https://learnemc.com/introduction-to-imbalance-difference-modeling',
 sensorTitle:'M12와 이더넷 전환부',sensor:'차동쌍의 길이만 맞추는 것으로 끝내지 않는다. 24 V / 0 V, 실드, 함체, 커넥터 핀과의 관계가 두 선에서 같은지도 본다. 특히 커넥터와 트랜스 앞 전환부를 작게 잘라 비교하기 좋다.',
 scopeTitle:'두 선을 한 도체로 합치지 않는다',scope:'외부 긴 케이블을 공통모드 포트로 줄여도 내부에서 차동으로 바뀌는 구간은 두 선을 남긴다. 여기서 차동이 거의 0이어도 공통모드는 남는다. 실제 수신기의 공통모드 허용 범위는 별도로 확인한다.',
 insight:'<b>균형은 “두 선끼리”뿐 아니라 “주변과의 관계”에도 있다.</b> 동일한 외란을 받는지부터 비교한다.',
 model:'길이 80 mm, 높이 12 mm, 폭 2 mm의 세 배선. 피해 선은 y=−8,+8 mm에 고정. 노이즈 선을 y=0에서 +4 mm로 이동. 발생원 양 끝 각각 1 kΩ, 피해 선 양 끝 각각 50 Ω. 이상적인 대칭 구조와 단일 비대칭을 비교한다.',
 formula:'V차동 = V₊ − V₋   (복소수 차)\nV공통 = (V₊ + V₋) / 2',approx:'01의 정전용량 행렬을 세 도체로 확장해 두 피해 노드의 전압을 푼다. E/H가 함께 존재하는 실제 계산과 차이가 남는다. 대칭 모델의 수치 잔차는 실제 제품에서 보장되는 무한한 제거 성능이 아니다.',
 takeaway:'배운 것: 차동 노이즈는 두 선의 전압 크기만 따로 봐서는 모른다.'},
 {names:['w_short','w_long','w_loaded'],labels:['A · 짧은 배선','B · 긴 배선','C · 종단 변경'],sub:['40 mm · 1 kΩ','120 mm · 1 kΩ','120 mm · 50 Ω'],title:'길이가 달라지면, 약해지는 주파수도 달라질까?',prompt:'주파수를 올려 보고, 길이와 끝의 저항을 바꿔 보자. 막대는 선로 위 13개 위치의 계산 전압이다.',measure:'배선 끝 저항에 걸린 전압',norm:'50 Ω 테브난 발생원 전압 1 V RMS 기준',unit:'V',defaultF:600,
 principleTitle:'길이는 파장과 비교한다',principle:'배선의 전기적 길이가 커지면 위치마다 위상과 전압이 달라진다. 끝에서 돌아온 파가 겹치면서 응답에 봉우리가 생긴다. 이 예에서는 길이가 길수록 첫 공진이 더 낮은 주파수로 들어온다.',source:'https://www.ti.com/document-viewer/lit/html/SSZTB23',
 sensorTitle:'20 m를 PCB 기생 C 하나로?',sensor:'긴 케이블의 공통모드·차동모드에는 각각 전파 속도와 종단이 있다. 외부 케이블 전체를 FDTD 격자로 채우기 전에 전송선 모델로 나누고, 커넥터 주변의 국부 결합을 3D로 보는 구성을 고려한다.',
 scopeTitle:'짧은 근사는 대역과 오차로 정한다',scope:'첫 가늠으로 ℓ/λ가 작은지 확인한다. λ/10도 오차를 보장하는 선은 아니다. 필요한 대역에서 전송선 모델과 비교해 짧은 근사의 오차가 충분히 작을 때 생략한다. 길이뿐 아니라 종단도 보존한다.',
 insight:'<b>높은 주파수에서 “길이 두 배 → 노이즈 두 배”는 통하지 않는다.</b> 피크 위치와 종단 의존성을 함께 본다.',
 model:'외란이 이미 배선 입력에 들어왔다고 둔 전달 실험이다. 외부 장이 케이블에 유도하는 입력 자체는 별도의 모델로 정한다. 높이 4 mm, 폭 4 mm. 길이 40 또는 120 mm. 발생원 내부 저항 50 Ω, 끝 저항 1 kΩ 또는 50 Ω. 1 V는 발생원 개방 전압이며 입력 포트 전압 자체가 아니다. 공기 중 모델이므로 PCB 유전체나 실제 케이블 속도 계수는 포함하지 않았다.',
 formula:'V끝/Vs = 1 / [(1+Rs/RL)cos(βℓ)\n               +j(Z₀/RL+Rs/Z₀)sin(βℓ)]\nλ = c/f  (이 공기 모델)',approx:'손실 없는 전송선 근사, Rs=50 Ω. Z₀는 폭/높이로 구한다. 50 Ω 종단은 이 선로의 Z₀와 같지 않으므로 “정합”으로 표시하지 않는다. 종단은 의도한 신호의 전달과 인터페이스 규격을 함께 고려해 정한다.',
 takeaway:'배운 것: 주파수를 올릴 때는 길이·위상·종단을 함께 본다.'}
];
let state={case:0,variant:0,index:0,field:'E',yaw:.62,pitch:.64};
let scene,renderer,camera,group,labels=[],profileStems=[],raf=0,contextLost=false;
const modelAvailable=()=>Boolean(renderer&&!contextLost);
const V=(x,y,z)=>new THREE.Vector3(x,y,z), S=.06;
const number=(v,d=2)=>v.toLocaleString('ko-KR',{maximumFractionDigits:d});
const current=()=>CASES[state.case], record=()=>DATA.runs[current().names[state.variant]];
function nearest(a,x){let j=0;for(let i=1;i<a.length;i++)if(Math.abs(a[i]-x)<Math.abs(a[j]-x))j=i;return j;}
function setFrequency(mhz){const f=record().freq;state.index=nearest(f,mhz);$('freq').value=1000*Math.log(f[state.index]/f[0])/Math.log(f.at(-1)/f[0]);updateNumbers();}
function formatMetric(v,unit){if(unit==='mV'&&v<.001)return '&lt;0.001 <small>mV</small>';return number(v,v>=100?1:3)+' <small>'+unit+'</small>';}
function loadCase(i){state.case=i;state.variant=0;const c=current();$('show-approx').disabled=i===3;if(i===3)$('show-approx').checked=false;$('approx-label').textContent=i===3?'이 사례는 실제 계산만 표시':'선택한 형상의 근사식도 보기';document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.case===i)));for(const [id,key] of [['question','title'],['prompt','prompt'],['measure-label','measure'],['normalization','norm'],['principle-title','principleTitle'],['principle','principle'],['sensor-title','sensorTitle'],['sensor','sensor'],['scope-title','scopeTitle'],['scope','scope'],['takeaway','takeaway']])$(id).textContent=c[key];$('principle-source').href=c.source;$('model-detail').innerHTML='<p>'+c.model+'</p>';$('approx-detail').innerHTML='<div class="formula">'+c.formula.replaceAll('\n','<br>')+'</div><p>'+c.approx+'</p>';$('insight').innerHTML=c.insight;$('variants').innerHTML=c.names.map((n,k)=>'<button data-variant="'+k+'" aria-pressed="'+(k===0)+'">'+c.labels[k]+'<span>'+c.sub[k]+'</span></button>').join('');document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>selectVariant(+b.dataset.variant));$('transfer-guide').hidden=i!==4;$('extra-impedance').hidden=i!==0;$('next').textContent=i===4?'센서에 적용하기 ↓':'다음 구조 →';const f=record().freq;$('freq-min').textContent=number(f[0])+' MHz';$('freq-max').textContent=number(f.at(-1))+' MHz';const ps=i===4?[50,300,600,1200]:[10,50,100,300];$('freq-presets').innerHTML=ps.map(x=>'<button data-freq="'+x+'">'+x+' MHz</button>').join('');document.querySelectorAll('[data-freq]').forEach(b=>b.onclick=()=>setFrequency(+b.dataset.freq));$('chart-note').textContent=(i===4?'가로축'+'은 주파수의 로그 눈금, 세로축은 전압. 막대 높이는 13개 위치의 |V|이며 같은 눈금을 쓴다.':'가로축은 주파수의 로그 눈금, 세로축은 전압. 같은 실험 안에서 동일한 기준 입력으로 비교한다.')+' 슬라이더는 저장된 주파수 샘플 중 가장 가까운 값을 선택한다.';setFrequency(c.defaultF);buildGeometry();updateField();resetCamera();chooseView(i>=2?'context':'model');}
function selectVariant(v){state.variant=v;document.querySelectorAll('[data-variant]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.variant===v)));updateNumbers();buildGeometry();updateField();drawContext();}
function updateNumbers(){const c=current(),r=record(),i=state.index,f=r.freq[i],val=r.value[i],base=DATA.runs[c.names[0]].value[i];$('freq-value').textContent=number(f,1)+' MHz';$('metric').innerHTML=formatMetric(val,c.unit);let comp='A를 기준으로 B / C를 비교해 보자.';if(c.names.length===2)comp='A를 기준으로 B를 비교해 보자.';if(state.variant&&base>.001){const ratio=val/base,db=20*Math.log10(Math.max(ratio,1e-15));comp='A 대비 '+number(ratio*100,1)+'% · '+(db>0?'+':'')+number(db,1)+' dB';}else if(state.case===3){comp=state.variant?'같은 구조의 대칭을 깨자 차동 성분이 생겼다.':'이상적 대칭에서의 수치 잔차 수준';}if(state.case===3){const cm=r.cm[i];comp+=' · 공통모드 '+number(cm,2)+' mV';}$('comparison').textContent=comp;const colors=c.names.map((n,k)=>'<span class="chart-key"><i class="line-key" style="--c:'+COLORS[k]+'"></i>'+c.labels[k]+'</span>');if($('show-approx').checked)colors.push('<span class="chart-key"><i class="line-key dash"></i>선택 형상의 근사</span>');$('chart-legend').innerHTML=colors.join('');updateTransferReading();drawChart();updateImpedance();updateStems();updateGeometryText();renderScene();drawContext();}
function fitCanvas(el){const d=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,el.clientWidth),h=Math.max(1,el.clientHeight);el.width=w*d;el.height=h*d;const x=el.getContext('2d');x.setTransform(d,0,0,d,0,0);return [x,w,h];}
function drawChart(){const [ctx,w,h]=fitCanvas($('chart')),c=current(),r=record();const pad={l:w<500?48:59,r:16,t:24,b:39},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;const all=c.names.map(n=>DATA.runs[n]);let ymax=Math.max(...all.flatMap(x=>x.value));if($('show-approx').checked)ymax=Math.max(ymax,...r.approx);const step=niceStep(ymax/4);ymax=Math.ceil(ymax/step)*step;const min=r.freq[0],max=r.freq.at(-1),fx=f=>pad.l+Math.log(f/min)/Math.log(max/min)*pw,fy=v=>pad.t+ph*(1-v/ymax);ctx.clearRect(0,0,w,h);ctx.font='12px system-ui';ctx.textBaseline='middle';ctx.fillStyle='#52656c';ctx.fillText(c.unit,pad.l,12);ctx.lineWidth=1;for(let y=0;y<=ymax+step*.1;y+=step){const py=fy(y);ctx.strokeStyle='#e1e6e3';ctx.beginPath();ctx.moveTo(pad.l,py);ctx.lineTo(w-pad.r,py);ctx.stroke();ctx.textAlign='right';ctx.fillText(number(y,y<2?2:0),pad.l-8,py);}const ticks=max>500?[10,30,100,300,1000,1500]:[5,10,30,100,300,500];let last=-1e9;for(const f of ticks){const px=fx(f);if(px-last<(w<500?39:46))continue;last=px;ctx.textAlign='center';ctx.fillText(number(f),px,h-19);}ctx.textAlign='right';ctx.fillText('MHz',w-pad.r,h-4);all.forEach((a,k)=>line(a.value,COLORS[k],k===state.variant?3.2:1.7,false));if($('show-approx').checked)line(r.approx,'#6d737e',2,true);const px=fx(r.freq[state.index]);ctx.strokeStyle='#506c77';ctx.lineWidth=1;ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(px,pad.t);ctx.lineTo(px,h-pad.b);ctx.stroke();ctx.setLineDash([]);all.forEach((a,k)=>{ctx.fillStyle=COLORS[k];ctx.strokeStyle='white';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(px,fy(a.value[state.index]),4.3,0,Math.PI*2);ctx.fill();ctx.stroke();});function line(vals,color,lw,dashed){ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.setLineDash(dashed?[6,5]:[]);ctx.beginPath();r.freq.forEach((f,i)=>{const x=fx(f),y=fy(vals[i]);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();ctx.setLineDash([]);}}
function niceStep(v){const p=10**Math.floor(Math.log10(v||1)),a=v/p;return (a<=1?1:a<=2?2:a<=2.5?2.5:a<=5?5:10)*p;}
function updateImpedance(){if(state.case!==0)return;const r=record(),R=10**+$('rv').value,f=r.freq[state.index]*1e6,cc=r.capacitance,jw=2*Math.PI*f;const val=jw*Math.abs(cc[1][0])/Math.hypot(2/R,jw*cc[1][1])*1000;$('rv-value').textContent=number(R,0)+' Ω';$('rv-result').innerHTML='<b>근사'+' '+number(val,3)+' mV</b> / 발생원 1 V · '+number(f/1e6,1)+' MHz';}
function fieldColor(t){const stops=[[18,38,54],[27,89,126],[42,155,163],[178,206,118],[255,210,96]];t=Math.max(0,Math.min(1,t));const a=Math.min(3,Math.floor(t*4)),u=t*4-a;return 'rgb('+stops[a].map((v,k)=>Math.round(v*(1-u)+stops[a+1][k]*u)).join(',')+')';}
function updateField(){const r=record();$('field-title').textContent=(state.case===4?'600':'100')+' MHz · '+(state.field==='E'?'전기장':'자기장')+' 크기 단면';$('field-note').textContent=(state.case===3?'패드 위치 x=16 mm를 자른 단면이다. ':'')+'위 주파수 슬라이더와 독립된 고정 주파수 결과다. 가로 y, 세로 z. 밝은 부분은 이 단면 안에서 장이 상대적으로 강한 위치다.';if(!$('field-drawer').open)return;const data=r.fields[state.field],[ctx,w,h]=fitCanvas($('field')),L=42,R=17,T=14,B=40,pw=w-L-R,ph=h-T-B;ctx.fillStyle='#142630';ctx.fillRect(0,0,w,h);const xfun=y=>L+(y+30)/60*pw,zfun=z=>T+(32-z)/32*ph;const yy=data.y,zz=data.z;for(let j=0;j<zz.length;j++)for(let i=0;i<yy.length;i++){const ya=i?(yy[i-1]+yy[i])/2:-30,yb=i<yy.length-1?(yy[i]+yy[i+1])/2:30,za=j?(zz[j-1]+zz[j])/2:0,zb=j<zz.length-1?(zz[j]+zz[j+1])/2:32;const a=Math.max(-30,ya),b=Math.min(30,yb),c=Math.max(0,za),d=Math.min(32,zb);ctx.fillStyle=fieldColor(data.db[j][i]/60+1);ctx.fillRect(xfun(a),zfun(d),xfun(b)-xfun(a)+.5,zfun(c)-zfun(d)+.5);}ctx.strokeStyle='#d0e6e0';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(L,zfun(0));ctx.lineTo(w-R,zfun(0));ctx.stroke();const cfg=r.cfg,ys=cfg.y||[0];ys.forEach((y,i)=>{ctx.strokeStyle=state.case===3?(i===0?'#8bc1ff':'#ef91c0'):(i===0?'#ffcd79':i===1?'#8bc1ff':'#ef91c0');ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(xfun(state.case===3&&cfg.pad&&i===0?-10:y-(cfg.w||2)/2),zfun(cfg.h));ctx.lineTo(xfun(y+(cfg.w||2)/2),zfun(cfg.h));ctx.stroke();});ctx.font='11px system-ui';ctx.fillStyle='#c6dbe4';ctx.textAlign='center';[-30,0,30].forEach(v=>ctx.fillText(v+'',xfun(v),h-20));ctx.textAlign='left';ctx.fillText('z mm',4,12);ctx.fillText('32',13,T+8);ctx.fillText('0',20,zfun(0));ctx.fillText('y mm',w-40,h-5);const cw=Math.min(135,w*.3),cx=w-R-cw;for(let i=0;i<cw;i++){ctx.fillStyle=fieldColor(i/cw);ctx.fillRect(cx+i,T+8,1,7);}ctx.fillStyle='#e5f0f4';ctx.font='10px system-ui';ctx.fillText('−60 dB',cx,T+29);ctx.textAlign='right';ctx.fillText('0 dB',w-R,T+29);}
function box(w,h,d,x,y,z,color,opacity=1){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.2,transparent:opacity<1,opacity,depthWrite:opacity===1}));m.position.set(x,y,z);group.add(m);return m;}
function tube(points,color,r=.025){const curve=new THREE.CatmullRomCurve3(points.map(p=>V(...p)));const m=new THREE.Mesh(new THREE.TubeGeometry(curve,32,r,7,false),new THREE.MeshBasicMaterial({color}));group.add(m);return m;}
function label(text,x,y,z,color){const el=document.createElement('div');el.className='label';el.textContent=text;if(color)el.style.borderColor=color;$('labels').appendChild(el);labels.push({el,pos:V(x,y,z)});}
function arrow(a,b,color){const av=V(...a),bv=V(...b);group.add(new THREE.ArrowHelper(bv.clone().sub(av).normalize(),av,av.distanceTo(bv),color,.17,.09));}
function buildOriginalGeometry(){const cfg=record().cfg;$('geometry-legend').innerHTML=state.case===2?'<span><i class="dot" style="--dot:#e9b766"></i>공유'+' 연결</span><span><i class="dot" style="--dot:#7acbb5"></i>기준면 / 접합</span>':'<span><i class="dot" style="--dot:#e9b766"></i>발생원</span><span><i class="dot" style="--dot:#86bfff"></i>피해 배선'+(state.case===3?' + / −':'')+'</span><span><i class="dot" style="--dot:#7acbb5"></i>귀환면</span>';if(state.case===4)$('geometry-legend').innerHTML='<span><i class="dot" style="--dot:#e9b766"></i>배선</span><span><i class="dot" style="--dot:#86bfff"></i>13개 지점의 계산 |V| · 동일 눈금</span>';drawFallback();if(!renderer)return;if(group){scene.remove(group);group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose());}});}group=new THREE.Group();scene.add(group);$('labels').innerHTML='';labels=[];profileStems=[];const L=cfg.L*S,h=cfg.h*S;box(10,.05,5,0,-.06,0,'#527069');const grid=new THREE.GridHelper(10,20,'#66827a','#58766d');grid.scale.z=.5;grid.position.y=-.025;group.add(grid);const ys=cfg.y||[0];ys.forEach((yp,k)=>{const z=yp*S,col=k===0?'#efb95e':k===1?'#77b3f7':'#e287b4';box(L,.045,(cfg.w||2)*S,0,h,z,col);[-1,1].forEach((sign,j)=>{const x=sign*L/2;if(cfg.kind==='shorted'&&sign===-1){box(.09,h,(cfg.w||2)*S,x,h/2,z,'#76c3ad');label('A · 면에 접합',x,.06,z+.45,'#76c3ad');}else{box(.07,h,.07,x,h/2,z,col,.9);box(.16,Math.min(.25,h*.65),Math.max(.16,(cfg.w||2)*S*.65),x,h*.42,z,k===0&&j===0&&cfg.kind!=='shorted'?'#edbb67':'#50698d');}});if(cfg.y){label(k===0?'노이즈 발생원':state.case===3?(k===1?'피해 +':'피해 −'):'피해 배선',L/2+.25,h+.25,z,col);}if(state.case===1){box(L,h,.015,0,h/2,z,col,.11);tube([[-L/2,h,z],[L/2,h,z],[L/2,.05,z],[-L/2,.05,z],[-L/2,h,z]],k===0?'#d9ac61':'#68b6d2',.017);arrow([1.3,.07,z],[-.1,.07,z],'#83d6b7');}});label('PEC 귀환면',-2.7,.03,1.7,'#7acbb5');if(cfg.kind==='coupled'){const near=cfg.y[0]*S;arrow([-.8,h+.1,near],[.7,h+.1,near],'#ffd588');}if(cfg.kind==='shorted'){label('B · 전류 주입 / ΔV',L/2+.15,h+.25,.15,'#f2c77d');arrow([1.5,h+.1,0],[.4,h+.1,0],'#f5c67b');}if(cfg.kind==='line'){label('Vs 1 V · Rs 50 Ω',-L/2,.1,.8,'#e9b766');label('끝 '+number(cfg.R)+' Ω',L/2,.1,.8,'#e9b766');for(let j=0;j<13;j++){const x=-L/2+j*L/12;const m=box(.055,1,.055,x,h+.5,0,'#7bb6ee',.85);profileStems.push(m);}label('|V| · 1 V 높이',-L/2-.2,h+1.25,0,'#86bfff');}updateStems();renderScene();}
function updateStems(){if(state.case!==4||!profileStems.length)return;const r=record(),h=r.cfg.h*S;profileStems.forEach((m,k)=>{const v=r.profile[k][state.index];m.scale.y=Math.max(.006,v);m.position.y=h+v/2;});}
function renderScene(){if(!renderer)return;const w=$('scene').clientWidth,h=$('scene').clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;const radius=w<480?16:14;camera.position.set(radius*Math.sin(state.yaw)*Math.cos(state.pitch),radius*Math.sin(state.pitch),radius*Math.cos(state.yaw)*Math.cos(state.pitch));camera.lookAt(0,.4,0);camera.updateProjectionMatrix();renderer.render(scene,camera);const used=[];labels.forEach(l=>{const p=l.pos.clone().project(camera),rw=l.el.offsetWidth||90,rh=l.el.offsetHeight||25;let x=Math.max(rw/2+5,Math.min(w-rw/2-5,(p.x+1)*w/2)),y=Math.max(rh/2+4,Math.min(h-rh/2-4,(1-p.y)*h/2));for(let t=0;t<15;t++){if(!used.some(q=>Math.abs(x-q.x)<(rw+q.w)/2+3&&Math.abs(y-q.y)<(rh+q.h)/2+3))break;y=Math.max(rh/2+4,Math.min(h-rh/2-4,y+(t%2?1:-1)*(rh+5)*Math.ceil((t+1)/2)));}used.push({x,y,w:rw,h:rh});l.el.style.left=x+'px';l.el.style.top=y+'px';});}
function drawFallback(){const cfg=record().cfg,ys=cfg.y||[0],h=cfg.h;let s='<rect x="20" y="40" width="460" height="160" rx="8" fill="#47675f"/><text x="28" y="228" fill="#cee3dc" font-size="16">귀환면 위 '+h+' mm · 길이 '+cfg.L+' mm</text>';ys.forEach((y,i)=>{const yy=115+y*3,col=i===0?'#edbb67':i===1?'#80b9fb':'#ee92bf';s+='<path d="M70 '+yy+' H430" stroke="'+col+'" stroke-width="'+(cfg.w||2)*2+'"/><text x="70" y="'+(yy-13)+'" fill="#f1f6f5" font-size="13">'+(cfg.kind==='pair_cm'?(i===0?'차동 +':'차동 −'):(i===0?'발생원 / 공유 연결':'피해 '+i))+'</text>';});if(cfg.kind==='pair_cm'&&cfg.pad)s+='<rect x="304" y="85" width="36" height="24" fill="#8bbfff"/>';$('fallback-svg').innerHTML=s;}
function populateQuality(){const rows=Object.entries(DATA.runs).map(([n,r])=>'<tr><td>'+n+'</td><td>'+number(r.meta.cells,0)+'</td><td>'+number(r.meta.elapsed_seconds,1)+' s</td><td>'+number(r.meta.final_energy_db,1)+' dB'+(r.meta.hit_limit?' · 횟수 제한':'')+'</td></tr>');$('quality-table').innerHTML=rows.join('');$('quality-summary').innerHTML=DATA.quality_html;}
// Revision: familiar circuit context before the numerical submodel.
Object.assign(CASES[2],{
 title:'모터가 전류를 쓸 때, 왜 센서값이 흔들릴까?',
 prompt:'주황색 귀환 전류가 지나가는 구간을 보자. 센서는 A를, ADC는 B를 기준으로 전압을 읽는다.',
 principleTitle:'센서의 0 V와 ADC의 0 V가 다르면',
 principle:'센서가 A 기준으로 만든 전압을 ADC는 B 기준으로 읽는다. 모터 귀환 전류 때문에 B가 ΔV만큼 움직이면, 이 연결에서 ADC가 읽는 전압에도 −ΔV가 섞인다. 신호선에 직접 노이즈를 쏘지 않아도 생기는 문제다.',
 measure:'두 기준점의 차이 |V_B − V_A|',
 insight:'<b>센서 출력은 그대로여도, 읽는 쪽의 기준이 움직일 수 있다.</b> 아래 수치는 공유 경로의 ΔV이고, ADC 오동작을 직접 계산한 값은 아니다.',
 model:CASES[2].model+' 연결 그림은 이 임피던스가 어디에 쓰이는지 설명한다. 센서·ADC·모터 전체를 이 FDTD 모델에 넣은 것은 아니다.',
 takeaway:'핵심: 신호선뿐 아니라, 신호를 읽는 두 회로가 어떤 기준 경로를 공유하는지 본다.'
});
Object.assign(CASES[3],{
 names:['dp_clean','dp_pad'],labels:['A · 나란한 두 선','B · 한쪽 패드 추가'],sub:['같은 단면 / 종단','+ 선에 8 × 8 mm'],
 title:'차동쌍 한쪽에만 테스트 패드가 붙으면?',
 prompt:'두 선에 같은 위상의 외란을 넣는다. 한쪽 패드만 추가했을 때, 받는 쪽에 차이가 생기는지 본다.',
 norm:'두 개의 50 Ω 발생원에 같은 위상 · 각각 1 V RMS 기준',
 principleTitle:'실제 배선의 패드·비아에서 깨지는 균형',
 principle:'커넥터에서 빠져나오는 배선, 한쪽에만 붙은 테스트 패드, 서로 다른 비아나 주변 구리로 균형이 깨질 수 있다. 이번에는 나란한 두 선을 유지하고 + 선의 구리 면적만 늘렸다. 기생 성분과 전달이 달라지면서 공통 외란의 일부가 차동 전압으로 나타난다.',
 source:'https://www.ti.com/lit/an/spraar7/spraar7.pdf',
 sensorTitle:'M12 핀에서 트랜스까지',
 sensor:'커넥터에서 배선이 퍼지는 구간, 패드와 비아, 테스트 포인트, 두 선 주변의 기준 도체를 본다. 이 사례는 두 신호선 중 한쪽의 금속 면적만 바꿔 비교한다.',
 model:'길이 80 mm, 높이 4 mm, 폭 2 mm, 중심 간격 4 mm의 나란한 PEC 배선 두 개다. 각 선의 양 끝은 50 Ω으로 기준면에 연결된다. 양쪽 왼쪽 포트를 같은 파형·위상으로 여기한다. B만 + 선에 x=12…20, y=−10…−2 mm의 8×8 mm 구리 패드를 추가한다. 공기 중 교육용 치수이며 100 Ω 이더넷 배선을 재현한 치수는 아니다. 정규화는 두 테브난 발생원 전압의 평균을 1 V RMS로 둔다.',
 formula:'V차동 = V₊ − V₋   (복소수 차)\nV공통 = (V₊ + V₋) / 2',
 approx:'이 사례에는 임의의 C 값을 넣은 근사 곡선을 표시하지 않는다. 같은 파형으로 여기한 두 포트와 실제 금속 패드를 함께 풀어, 수신단의 복소 전압 차이를 구했다. TI의 배선 지침은 대칭 배선·부품 배치의 근거이고, 여기의 치수와 수치는 별도로 구성한 교육용 실험이다.',
 insight:'<b>차동쌍 사이에 다른 선이 들어가야만 생기는 문제가 아니다.</b> 한쪽 패드·비아·주변 도체가 달라도 균형이 깨진다.',
 takeaway:'핵심: 나란한 두 선의 길이뿐 아니라, 패드·비아·주변 환경도 두 선이 비슷하게 만나도록 본다.'
});
Object.assign(CASES[4],{
 title:'들어온 노이즈가, 선 끝에서 더 커질 수 있을까?',
 prompt:'600 MHz 부근에서 A → B로 길이를 늘리고, B → C로 끝 저항을 바꿔 보자. 같은 발생원 조건에서도 끝 전압이 달라진다.',
 principleTitle:'노이즈에도 반사와 공진이 적용된다',
 principle:'앞의 예들은 노이즈가 다른 회로에 섞이는 경로를 봤다. 이번에는 노이즈가 이미 입력에 들어왔다고 놓고, 선 끝까지 어떻게 전달되는지 본다. 돌아온 파와 진행하는 파가 겹치면서 특정 주파수의 전압이 커질 수 있다.',
 insight:'<b>유입량을 정했다면, 끝까지 전달되는 양도 본다.</b> 길이를 늘리면 공진 주파수가 이동하고, 끝 저항을 바꾸면 반사와 부하 조건이 함께 달라진다.',
 takeaway:'핵심: 01~04로 유입 경로를 찾고, 전기적으로 긴 경로라면 05처럼 주파수별 전달도 확인한다.'
});
state.zoom=1;state.pan=[0,.4,0];state.view='model';
let dragPointers=new Map(), gesture=null;
function chooseView(mode){state.view=mode;const isModel=mode==='model';$('context-svg').style.display=isModel?'none':'block';$('labels').style.display=isModel&&modelAvailable()?'block':'none';if(renderer)renderer.domElement.style.display=isModel&&modelAvailable()?'block':'none';$('fallback').style.display=isModel&&!modelAvailable()?'block':'none';['zoom-in','zoom-out','view-top','view-reset'].forEach(id=>$(id).disabled=!modelAvailable());$('camera-buttons').hidden=!isModel;$('view-context').setAttribute('aria-pressed',!isModel);$('view-model').setAttribute('aria-pressed',isModel);$('view-context').hidden=state.case<2;$('view-model').hidden=state.case<2;$('scene-hint').textContent=isModel?'드래그: 회전 · 휠: 확대/축소 · 방향키·+/− · Home: 복원':'실제 연결을 이해하는 그림 · 3D 버튼으로 계산한 형상 보기';renderScene();drawContext();}
function resetCamera(){state.yaw=.62;state.pitch=.64;state.zoom=1;state.pan=[0,.4,0];renderScene();}
function initScene(){
 try{
  if(!window.THREE)throw Error('Three unavailable');scene=new THREE.Scene();scene.background=new THREE.Color('#142630');camera=new THREE.PerspectiveCamera(38,1,.1,150);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));const el=renderer.domElement;el.tabIndex=0;el.setAttribute('aria-label','3D 형상: 드래그 회전, 휠 확대와 축소, 오른쪽 드래그 이동. 방향키 회전, +와 - 확대와 축소, Home 복원.');el.style.touchAction='none';$('scene').insertBefore(el,$('labels'));
  scene.add(new THREE.HemisphereLight('#d9efff','#526064',2.4));const light=new THREE.DirectionalLight('#fff1d2',2.4);light.position.set(4,9,6);scene.add(light);
  el.addEventListener('contextmenu',e=>e.preventDefault());
  el.addEventListener('keydown',e=>{
    if(!modelAvailable()||e.ctrlKey||e.metaKey||e.altKey)return;
    const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','_','Home'];
    if(!keys.includes(e.key))return;e.preventDefault();
    if(e.key==='Home'){resetCamera();return;}
    if(e.key==='ArrowLeft')state.yaw+=.18;if(e.key==='ArrowRight')state.yaw-=.18;
    if(e.key==='ArrowUp')state.pitch=Math.min(1.52,state.pitch+.1);if(e.key==='ArrowDown')state.pitch=Math.max(.08,state.pitch-.1);
    if(e.key==='+'||e.key==='=')state.zoom=Math.max(.35,state.zoom/1.2);
    if(e.key==='-'||e.key==='_')state.zoom=Math.min(3,state.zoom*1.2);renderScene();
  });
  $('scene').addEventListener('wheel',e=>{if(!modelAvailable()||state.view!=='model'||!Number.isFinite(e.deltaY)||!e.deltaY)return;e.preventDefault();const dy=Math.max(-200,Math.min(200,e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?el.clientHeight:1)));state.zoom=Math.max(.35,Math.min(3,state.zoom*Math.exp(dy*.0012)));renderScene();},{passive:false});
  const snapshot=()=>{const p=[...dragPointers.values()];return {x:p.reduce((a,b)=>a+b.x,0)/p.length,y:p.reduce((a,b)=>a+b.y,0)/p.length,d:p.length>1?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0,n:p.length,pan:p.length>1||p[0].button!==0||p[0].shift};};
  el.addEventListener('pointerdown',e=>{e.preventDefault();el.focus({preventScroll:true});dragPointers.set(e.pointerId,{x:e.clientX,y:e.clientY,button:e.button,shift:e.shiftKey});gesture=snapshot();el.setPointerCapture(e.pointerId);el.style.cursor='grabbing';});
  el.addEventListener('pointermove',e=>{if(!dragPointers.has(e.pointerId))return;const old=dragPointers.get(e.pointerId);dragPointers.set(e.pointerId,{...old,x:e.clientX,y:e.clientY});const g=snapshot(),dx=g.x-gesture.x,dy=g.y-gesture.y;if(g.n===gesture.n){if(g.n>1&&gesture.d>0&&g.d>0)state.zoom=Math.max(.35,Math.min(3,state.zoom*gesture.d/g.d));if(g.pan){const target=new THREE.Vector3(...state.pan),scale=2*camera.position.distanceTo(target)*Math.tan(camera.fov*Math.PI/360)/el.clientHeight;const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,1);target.addScaledVector(right,-dx*scale).addScaledVector(up,dy*scale);state.pan=target.toArray();}else{state.yaw-=dx*.007;state.pitch=Math.max(.08,Math.min(1.52,state.pitch+dy*.007));}}gesture=g;renderScene();});
  const end=e=>{dragPointers.delete(e.pointerId);gesture=dragPointers.size?snapshot():null;el.style.cursor=dragPointers.size?'grabbing':'grab';};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('lostpointercapture',end);
  el.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;dragPointers.clear();gesture=null;chooseView(state.view);});el.addEventListener('webglcontextrestored',()=>{contextLost=false;buildGeometry();chooseView(state.view);});el.style.cursor='grab';
 }catch(e){renderer=null;$('fallback').style.display='block';}
}
function renderScene(){
 if(!modelAvailable()||state.view!=='model')return;const w=$('scene').clientWidth,h=$('scene').clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;const radius=(w<480?16:14)*state.zoom,target=new THREE.Vector3(...state.pan);camera.position.set(radius*Math.sin(state.yaw)*Math.cos(state.pitch),radius*Math.sin(state.pitch),radius*Math.cos(state.yaw)*Math.cos(state.pitch)).add(target);camera.lookAt(target);camera.updateProjectionMatrix();renderer.render(scene,camera);const used=[],leaders=[];
 labels.forEach(l=>{const p=l.pos.clone().project(camera),rw=l.el.offsetWidth||90,rh=l.el.offsetHeight||25;let x=Math.max(rw/2+5,Math.min(w-rw/2-5,(p.x+1)*w/2)),y=Math.max(rh/2+4,Math.min(h-rh/2-4,(1-p.y)*h/2));for(let t=0;t<15;t++){if(!used.some(q=>Math.abs(x-q.x)<(rw+q.w)/2+3&&Math.abs(y-q.y)<(rh+q.h)/2+3))break;y=Math.max(rh/2+4,Math.min(h-rh/2-4,y+(t%2?1:-1)*(rh+5)*Math.ceil((t+1)/2)));}used.push({x,y,w:rw,h:rh});l.el.style.left=x+'px';l.el.style.top=y+'px';leaders.push({ax:(p.x+1)*w/2,ay:(1-p.y)*h/2,x,y,color:l.el.style.borderColor||'#8daab7'});});
 if(state.case===3){let svg=document.getElementById('scene-leaders');if(!svg){svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.id='scene-leaders';svg.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';$('labels').insertBefore(svg,$('labels').firstChild);}svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=leaders.map(l=>`<path d="M${l.ax} ${l.ay}L${l.x} ${l.y}" fill="none" stroke="${l.color}" stroke-width="1" opacity=".75"/><circle cx="${l.ax}" cy="${l.ay}" r="3" fill="${l.color}"/>`).join('');}
}
function buildGeometry(){
 if(state.case!==3){buildOriginalGeometry();return;}
 $('geometry-legend').innerHTML='<span><i class="dot" style="--dot:#8bbfff"></i>차동'+' + 선</span><span><i class="dot" style="--dot:#ed94c6"></i>차동 − 선</span><span>동일한 공통모드 외란 입력</span>';drawFallback();if(!renderer)return;
 if(group){scene.remove(group);group.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());});}group=new THREE.Group();scene.add(group);$('labels').innerHTML='';labels=[];profileStems=[];const c=record().cfg,h=c.h*S,L=c.L*S;box(10,.05,5,0,-.06,0,'#527069');const grid=new THREE.GridHelper(10,20,'#66827a','#58766d');grid.scale.z=.5;grid.position.y=-.025;group.add(grid);
 c.y.forEach((y,k)=>{const z=y*S,col=k?'#ed94c6':'#8bbfff';box(L,.045,2*S,0,h,z,col);[-1,1].forEach(s=>{box(.07,h,.07,s*L/2,h/2,z,col);box(.16,h*.6,.12,s*L/2,h*.45,z,'#526889');});label(k?'− 선 · 수신단':'+ 선 · 수신단',L/2,h,z,col);arrow([-L/2-.65,h,z],[-L/2-.05,h,z],'#f6c476');});if(c.pad){box(8*S,.045,8*S,16*S,h,-6*S,'#8bbfff');label('+ 선에만 추가된 패드',16*S,h,-6*S,'#8bbfff');}label('같은 위상 외란',-L/2-.3,h+.3,-.6,'#f6c476');label('PEC 기준면',-2,.05,1.7,'#7acbb5');renderScene();
}
function updateGeometryText(){const c=record().cfg;let s='<b>길이 '+c.L+' mm</b> · 귀환면 높이 '+c.h+' mm';if(c.y)s+=' · 중심 간격 '+Math.abs(c.y[1]-c.y[0])+' mm';else s+=' · 폭 '+c.w+' mm';if(state.case===4){const lambda=299792.458/record().freq[state.index];s+='<br>공기 중 ℓ/λ = '+number(c.L/lambda,3)+' · 끝 저항 '+number(c.R)+' Ω';}else if(state.case===3)s+='<br>두 신호선만 존재 · '+(c.pad?'+ 선에만 8×8 mm 패드':'같은 단면의 두 선');else if(state.case===2)s+='<br>계산 범위: 공유 경로의 Z → ΔV. 전체 모터·ADC 회로는 설명용.';else s+='<br>회색 면: 무한 PEC 귀환면의 일부를 잘라 표시';$('geometry').innerHTML=s;}
function drawContext(){
 if(state.view!=='context'||state.case<2)return;const root=$('context-svg'),w=$('scene').clientWidth,h=$('scene').clientHeight;root.setAttribute('viewBox',`0 0 ${w} ${h}`);const narrow=w<500,fs=narrow?13:15,bw=narrow?94:130,left=20,right=w-20-bw,cx=w/2;let s='<defs><marker id="arr-o" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto-start-reverse"><path d="M0 0L8 4L0 8Z" fill="#f4bd69"/></marker><marker id="arr-b" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto-start-reverse"><path d="M0 0L8 4L0 8Z" fill="#8bbfff"/></marker></defs>';
 const path=(d,c='#87a6b2',width=2,end='')=>s+=`<path d="${d}" fill="none" stroke="${c}" stroke-width="${width}" ${end?`marker-end="url(#${end})"`:''}/>`;
 const rect=(x,y,ww,hh,fill='#28434e',stroke='#698d9e',rr=7)=>s+=`<rect x="${x}" y="${y}" width="${ww}" height="${hh}" rx="${rr}" fill="${fill}" stroke="${stroke}"/>`;
 const text=(t,x,y,color='#e6f0f5',size=fs,anchor='middle')=>s+=`<text x="${x}" y="${y}" text-anchor="${anchor}" fill="${color}" font-size="${size}" font-family="system-ui,sans-serif">${t}</text>`;
 const block=(x,y,title,sub)=>{rect(x,y,bw,57);text(title,x+bw/2,y+23);text(sub,x+bw/2,y+43,'#bed1da',fs-1);};
 if(state.case===2){
  const a=left+bw/2,b=right+bw/2,yy=h-69;block(left,28,'24 V 전원','0 V = A');block(right,28,'모터 드라이버','급변 전류');block(left,153,'센서','출력 기준 A');block(right,153,'ADC','측정 기준 B');
  path(`M${left+bw} 49H${right}`,'#f4bd69',3,'arr-o');text('+24 V',cx,36,'#f4bd69',fs-1);path(`M${a} 85V105H8V${yy}H${a}`,'#83bea8',2);path(`M${a} 210V${yy}`,'#83bea8',2);path(`M${b} 85V124H${w-8}V${yy}H${b}`,'#f4bd69',3,'arr-o');text('귀환',w-9,141,'#f4bd69',fs-2,'end');
  path(`M${left+bw} 176H${right}`,'#8bbfff',2,'arr-b');text('센서 신호',cx,160,'#8bbfff',fs-1);path(`M${b} 210V${yy}`,'#83bea8',2);path(`M${a} ${yy}H${b}`,'#f4bd69',state.variant?9:4);rect(cx-43,yy-15,86,30,'#58452a','#f4bd69',4);text('공유 Z',cx,yy+5,'#ffdb9e',fs);path(`M${cx+20} ${yy+26}H${cx-22}`,'#f4bd69',2,'arr-o');text('A',a,yy+24,'#a7e0c5');text('B',b,yy+24,'#f4bd69');text('ADC 입력 = 센서 출력 − (V_B − V_A)',cx,h-12,'#d7e9e9',narrow?12:15);text('연결 설명 · 주황 구간만 Z로 계산',cx,117,'#b8ced9',fs-1);
 }else if(state.case===3){
  const x1=narrow?75:150,x2=w-x1,py=161,ny=193;rect(12,83,w-24,173,'#29463e','#5d8675');path(`M${x1} ${py}H${x2}`,'#8bbfff',13);path(`M${x1} ${ny}H${x2}`,'#ed94c6',13);text('+',x1-18,py+5,'#8bbfff',18);text('−',x1-18,ny+5,'#ed94c6',18);path(`M22 177H${x1-33}`,'#f4bd69',3,'arr-o');text('같은 외란',x1,54,'#f4bd69');text('2개 발생원 · 같은 위상',x1,73,'#b8ced9',fs-2);text('차동 수신',x2,285,'#e6f0f5');text('|V₊ − V₋|',x2,306,'#b8ced9',fs-1);rect(x2+10,py-15,49,64,'#28434e','#698d9e',5);path(`M${x2} ${py}H${x2+10}M${x2} ${ny}H${x2+10}`,'#c5d8e2',2);text('+',x2+19,py+4,'#8bbfff',11);text('−',x2+19,ny+4,'#ed94c6',11);text('VΔ',x2+38,180,'#dcebf2',12);text('배선 평면도 · 입력/측정은 기호',cx,h-12,'#b8ced9',fs-1);
  const xp=x1+(x2-x1)*.7;if(record().cfg.pad){rect(xp-21,105,42,56,'#8bbfff','#b3d7ff',0);text('한쪽 패드',xp,95,'#8bbfff',fs);}else{text('같은 단면',cx,132,'#b8ced9',fs);}text('PEC 기준면은 두 선 아래',cx,238,'#9bc9b2',fs-1);
 }else{
  const r=record(),i=state.index,x1=narrow?55:110,maxL=w-2*x1,x2=x1+maxL*r.cfg.L/120,y=213;
  text('노이즈가 이미 입력에 들어온 상황',cx,32,'#c6dce4',fs);text('발생원 1 V',x1,62,'#f4bd69',fs);text('Rs = 50 Ω',x1,81,'#b8ced9',fs-1);path(`M${x1} ${y}H${x2}`,'#f4bd69',4);path(`M${x2} ${y}V267H${x1}V261M${x1} 237V${y}`,'#82b79f',2);s+=`<circle cx="${x1}" cy="249" r="12" fill="#142630" stroke="#f4bd69" stroke-width="2"/>`;text('~',x1,253,'#f4bd69',19);rect(x1-6,218,12,12,'#58452a','#f4bd69',1);rect(x2-8,225,16,25,'#4d6893','#92acd3',2);text(number(r.cfg.R)+' Ω',x2,287,'#c5d8e2',fs-1);
  r.profile.forEach((p,k)=>{const x=x1+(x2-x1)*k/12,yy=y-70*p[i];path(`M${x} ${y}V${yy}`,'#8bbfff',3);});text('배선 '+r.cfg.L+' mm',cx,307,'#c5d8e2',fs);text('막대: 각 위치의 |V| · 화살표: 진행 / 반사',cx,328,'#b8ced9',fs-2);text('끝 전압 '+number(r.value[i],3)+' V',cx,h-12,'#ffe0a7',fs+1);if(x2-x1>100){path(`M${x1+20} 187H${x2-20}`,'#f4bd69',2,'arr-o');path(`M${x2-20} 160H${x1+20}`,'#8bbfff',2,'arr-b');}
 }
 root.innerHTML=s;
}
$('view-context').onclick=()=>chooseView('context');$('view-model').onclick=()=>chooseView('model');$('zoom-in').onclick=()=>{state.zoom=Math.max(.35,state.zoom/1.2);renderScene();};$('zoom-out').onclick=()=>{state.zoom=Math.min(3,state.zoom*1.2);renderScene();};

document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>loadCase(+b.dataset.case));$('freq').oninput=()=>{const r=record(),f=r.freq[0]*(r.freq.at(-1)/r.freq[0])**(+$('freq').value/1000);state.index=nearest(r.freq,f);updateNumbers();};$('show-approx').onchange=updateNumbers;$('rv').oninput=updateImpedance;$('field-drawer').ontoggle=updateField;['E','H'].forEach(k=>$('field-'+k.toLowerCase()).onclick=()=>{state.field=k;$('field-e').setAttribute('aria-pressed',k==='E');$('field-h').setAttribute('aria-pressed',k==='H');updateField();});$('view-top').onclick=()=>{state.pitch=1.51;state.yaw=0;renderScene();};$('view-reset').onclick=resetCamera;$('next').onclick=()=>{if(state.case===4){$('sensor-map').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});return;}loadCase(state.case+1);$('lesson').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});};
window.addEventListener('resize',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{drawChart();renderScene();updateField();drawContext();});});initScene();populateQuality();loadCase(0);
window.emcLesson={state,CASES,DATA,loadCase,selectVariant,setFrequency};

function updateTransferReading(){
  const f=record().freq[state.index];
  $('freq').setAttribute('aria-valuetext',number(f,1)+' MHz · 저장된 샘플');
  document.querySelectorAll('[data-freq]').forEach(b=>b.setAttribute('aria-pressed',String(nearest(record().freq,+b.dataset.freq)===state.index)));
  if(state.case!==4)return;
  const values=CASES[4].names.map(n=>DATA.runs[n].value[state.index]);
  $('transfer-reading').textContent=number(f,1)+' MHz의 저장값: A '+number(values[0],3)+' V → B '+number(values[1],3)+' V → C '+number(values[2],3)+' V. 모두 발생원 개방 전압 1 V RMS 기준.';
}
