/* Test definitions are proposed, not results or an executable solver mesh. */
const TEST_PLAN = {
  revision:'test-plan-09', baseline:'lab-review-03', cableEvidence:'cable-drawing-01', solverRun:false,
  defaults:{length:120,pitch:24,height:20,wiring:'same',shield:'floating',cmCap:0},
  sources:{
    solver:{label:'openEMS · FDTD, 경계·여기·종료 기준',url:'https://docs.openems.de/python/openEMS/openEMS.html'},
    ports:{label:'openEMS · 포트와 참조 임피던스',url:'https://docs.openems.de/python/openEMS/ports.html'},
    lumped:{label:'CSXCAD · 집중 R/L/C',url:'https://docs.openems.de/python/CSXCAD/CSProperties/CSPropLumpedElement.html'},
    example:{label:'openEMS · 공식 마이크로스트립 예제',url:'https://docs.openems.de/python/openEMS/Tutorials/MSL_NotchFilter.html'},
    emc:{label:'TI · 케이블과 잡음 결합',url:'https://www.ti.com/lit/pdf/snla016'},
    setup:{label:'ATLAS · 확인된 실험실 구성',url:'../porta-lab-setup/'},
    pcb:{label:'ATLAS · 기존 PCB 해석과 수렴 한계',url:'../porta-pcb/'},
    audit:{label:'이번에 확인한 기존 해석·T2 자료',url:'#pcb-audit-section'},
    cable:{label:'사용 케이블 · Northwire 47674-1 Rev C',url:'#cable-spec-section'},
    magneticModels:{label:'제조사 예시 · 트랜스의 회로/S-파라미터 모델',url:'https://www.we-online.com/en/components/products/WE-LAN'},
    phy:{label:'Microchip · LAN9354 데이터시트',url:'https://ww1.microchip.com/downloads/aemDocuments/documents/UNG/ProductDocuments/DataSheets/LAN9354-Data-Sheet-DS00001926.pdf'}
  },
  tests:[
    {id:'check',code:'00',title:'계산 도구부터 검증',short:'포트·격자',scene:'coupon',kind:'reference',
      plain:'이미 알려진 간단한 선로를 먼저 계산해서, 우리가 계산 도구를 올바르게 쓰는지 확인합니다.',
      route:'공식 예제 → 같은 조건으로 실행 → 포트·격자·경계 점검',
      question:'모델을 잘못 만들어 생긴 신호를 실제 잡음으로 착각하지 않으려면?',
      input:'공식 마이크로스트립 예제의 포트 1에서 가우시안 펄스 입력. 먼저 예제 조건을 재현합니다.',
      reference:'마이크로스트립 아래의 기준 도체. 포트의 전압·전류 방향과 측정면을 명시합니다.',
      probe:'포트 1의 반사, 포트 2의 전달, 입력·출력·손실 전력과 잔류 에너지.',
      compare:'공식 스텁 예제 → 스텁을 제거한 균일 선로 → 격자 세분화·포트 위치·외부 경계 비교.',
      included:'시험용 전송선, 유전체, 포트와 외부 경계. 현재 센서와 무관한 계산 검증용 구조입니다.',
      excluded:'LAN9354·20 m 케이블·모터. 이 시험의 정상 동작이 제품의 정상 동작을 뜻하지 않습니다.',
      decision:'포트 방향·기본 응답·종료 상태를 확인하고, 격자를 바꿔도 초기 판단이 유지되면 케이블 시험으로 이동합니다.',
      limitation:'이 계획 화면은 공식 예제의 구조를 설명합니다. 실제로 실행한 예제와 검증 상태는 위의 첫 계산 기록에서 별도로 확인합니다.',
      metrics:[['S11 / S21','복소수 · 주파수별'],['전력 균형','입사·반사·전달·손실'],['격자·기록 길이 영향','조건을 바꾼 두 결과의 차이']],
      sources:['example','solver','ports'], next:'power'},
    {id:'power',code:'01',title:'전원 잡음이 신호쌍으로 넘어오는가',short:'전원 → Ethernet',scene:'coupon',kind:'dm',
      plain:'전원 두 묶음 사이에 잡음을 넣고, Ethernet 쌍 1과 쌍 2에 생기는 잡음을 각각 읽습니다. 100BASE-TX의 신호선 네 선을 모두 포함합니다.',
      route:'전원 + ↔ 0 V 사이의 흔들림 → 같은 케이블 속 결합 → Ethernet 두 쌍 각각 관측',
      question:'현재의 +/+ · 0 V/0 V 배선이 Ethernet에 잡음을 전달하는 경로가 되는가?',
      input:'짧은 케이블 시험편의 +24 V 묶음과 0 V 묶음 사이에 작은 교류 잡음을 넣습니다. 시험용 소스 저항은 100 Ω로 시작합니다.',
      reference:'이 입력의 되돌아가는 선은 0 V 두 선입니다. 실제 24 V 전원 위에 겹치는 작은 변화만 다루며 실제 잡음 크기는 아직 미정입니다.',
      probe:'반대쪽 Ethernet 두 쌍 각각의 차동전압 Vd, 시험 기준판에 대한 공통모드 전압 Vcm, 전원 입력에서 실제로 형성된 전압 Vin.',
      compare:'물리적 네 꼬임쌍과 길이를 유지한 채 전원 핀 배정만 +/+·0/0 ↔ +/0·+/0로 바꿉니다. 실드는 양끝 미접속을 유지합니다.',
      included:'8선·절연체·실드·정해진 시험 종단을 가진 0.1–0.4 m의 국부 시험편. 이는 실제 20 m 전체가 아닙니다.',
      excluded:'SMPS의 스위칭 회로·모터·실제 PHY. Ethernet에는 양끝 각각 100 Ω 차동 시험 종단, 전원 먼 끝에도 100 Ω 시험 부하를 둡니다.',
      decision:'H(f)=Vd,out/Vin을 비교합니다. 차이가 수치 불확실성보다 크고 다른 가정에서도 유지되면, 실제 종단과 긴 케이블 모델에서 우선 검증할 후보로 남깁니다.',
      limitation:'이 비율은 명시한 소스·종단 아래의 전압 전달함수입니다. S21, 실제 수신 전압, CRC 오류율과 동일하지 않습니다.',
      metrics:[['Ethernet 쌍 1 · 잡음 전달','Vd / Vin · 별도 결과'],['Ethernet 쌍 2 · 잡음 전달','Vd / Vin · 별도 결과'],['배선 변경 전후 차이','두 쌍 각각 Vd·Vcm · 수치 오차 포함']],
      sources:['cable','solver','ports','lumped','emc','setup'],next:'common'},
    {id:'common',code:'02',title:'전원 배선 전체의 흔들림 · 실드 끝 연결 비교',short:'실드 끝 연결 비교',scene:'coupon',kind:'cm',
      plain:'전원 +와 0 V를 주변 기준에 대해 함께 흔듭니다. 실드를 계속 포함한 채 끝 연결을 바꾸고, Ethernet 두 쌍에 넘어오는 잡음을 비교합니다. 외부 RF를 쏘는 시험은 이 계획에 넣지 않았습니다.',
      route:'전원 네 선을 시험판에 대해 함께 흔듦 → 실드 미접속 / 한끝 / 양끝 비교 → Ethernet 두 쌍 관측',
      example:'예: 시험판에서 봤을 때 24 V / 0 V가 25 V / 1 V가 되면, 전원 차이는 여전히 24 V지만 두 묶음이 함께 1 V 움직였습니다. 개념 설명용 숫자이며 실제 잡음 크기가 아닙니다.',
      question:'전원 네 선의 전위가 함께 흔들릴 때, 양끝 미접속 실드는 어떤 역할을 하는가?',
      input:'①-A는 + 두 선의 묶음 단자에, ①-B는 0 V 두 선의 묶음 단자에 연결됩니다. 각 단자와 아래 시험판 사이에 있는 두 AC 소스를 같은 위상으로 구동합니다. 소스 저항은 각각 50 Ω입니다.',
      reference:'두 소스의 리턴은 유한한 시험 기준판입니다. 이 주입 연결은 시험용이며 실험실에 그 배선이 있었다고 가정하지 않습니다.',
      probe:'Vin,CM=(V+ + V0)/2−V판, Ethernet의 Vd와 Vcm, 실드·기준판 쪽 전류 및 전력.',
      compare:'현재의 양끝 미접속 → 분기 끝만 접속 → 양끝 접속을 각각 계산합니다. 접속선의 실제 길이·임피던스를 모델에 넣고 전원 핀 배정은 고정합니다.',
      included:'같은 8선 시험편, 실드와 시험 기준판. 기준판까지의 거리와 신호쌍의 공통모드 종단도 민감도 항목입니다.',
      excluded:'건물 PE·철제 테이블·SMPS 케이스가 모두 같은 이상적 접지라는 가정. 실제 장치의 그 연결은 전체 모델에서 별도로 확인합니다.',
      decision:'공통모드가 차동전압으로 바뀌는 전달과 실드 전류를 함께 비교합니다. 접속이 항상 유리하다고 미리 정하지 않습니다.',
      limitation:'확인된 케이블은 알루미늄/Mylar 포일 + 36 AWG 구리 편조이며 편조 피복률은 최소 85% 규격입니다. 화면의 망 무늬·원형 실드는 근사입니다. 단일 등가 실드는 초기 가정이고, 포일-편조 접촉·포일 두께·전달 임피던스는 아직 미확인입니다.',
      metrics:[['Ethernet 쌍 1 · 잡음 전달','Vd / Vin,CM · 별도 결과'],['Ethernet 쌍 2 · 잡음 전달','Vd / Vin,CM · 별도 결과'],['실드·기준판 전류','A/V · 방향·리턴 명시']],
      sources:['cable','solver','ports','emc','setup'],next:'pcb'},
    {id:'pcb',code:'03',title:'기존 PCB 해석을 재사용하고 잡음 전달을 보완',short:'기존 PCB + EMC 보완',scene:'pcb',kind:'pcb',
      plain:'두 PCB 구간의 SI 해석은 ATLAS에 이미 있습니다. 기존 형상과 자료를 재사용하고, 새 작업은 공통모드 잡음의 전달·변환과 T2·실장 부하를 포함한 응답에 집중합니다.',
      route:'구간 A: M12 측 PCB 패드 → T2 케이블측 패드 / 구간 B: T2 PHY측 패드 → LAN9354 패드',
      example:'T2는 설계 자료에 HX1260FNLT로 명시돼 있습니다. PCB는 실제 구리 형상으로, T2는 검증한 등가회로 또는 다중포트 모델로 표현해 이어 붙이는 방식을 제안합니다. 나누어 계산해도 최종 목표에는 트랜스가 포함됩니다.',
      question:'케이블에서 넘어온 잡음이 수신단 쪽으로 전달·변환되는 구간은 어디인가?',
      input:'M12 측 PCB 경계 또는 T2의 PHY측 패드에서 차동 / 공통모드를 각각 구동합니다. 주입 모드와 반환 도체를 구간별로 정의합니다.',
      reference:'각 PCB의 로컬 GND. 함체·실드·기준판 연결은 별도의 포트 또는 임피던스로 보존합니다.',
      probe:'T2 또는 U6 패드의 두 도체 전압·전류. 기준 임피던스를 명시한 뒤 차동/공통모드 전달과 변환으로 정리합니다.',
      compare:'기존 차동 SI 결과와 원본을 먼저 점검합니다. 케이블측의 저장된 4개 차동 포트만으로는 공통모드 응답을 얻을 수 없어 포트를 보완해야 합니다. PHY측은 원본에 남은 도체별 응답의 재사용 가능성부터 확인합니다.',
      included:'ATLAS의 제조 Gerber 기반 신호·기준 구리·비아와 64핀 접점 근사. 3D의 두 구간 전환은 별개의 해석 경계를 보여줍니다.',
      excluded:'현재 PCB 형상 보기에는 T2 내부 전기 모델과 TVS/PHY의 완전한 실장 부하가 없습니다. HX1260FNLT 품번과 CT 핀의 설계 연결은 확인했고, 모델 파라미터·완전한 부하망의 검증이 남았습니다.',
      decision:'같은 100 MHz SI 질문을 기본 작업으로 반복하지 않습니다. 01·02에서 의미 있는 경로가 보이면, 해당 주파수의 공통모드 변환과 T2·실장 부하가 포함된 전달을 추가 계산합니다. 새 모델마다 격자·관측 시간을 바꿔도 잡음 경로 판단이 유지되는지 확인합니다.',
      limitation:'표시 구리는 실제 자료이지만 마커는 시험 위치 설명입니다. 이 마커 자체가 확정된 solver 포트 상자는 아닙니다.',
      metrics:[['Sdd / Scd / Sdc / Scc','모드·포트 순서와 참조값 포함'],['소자 결합 후 패드 Vd / Vcm','실제 종단 자료 필요'],['패시브 모델의 일관성','수동성·상호성·조건 변경 영향']],
      sources:['audit','pcb','magneticModels','ports','solver','phy'],next:'system'},
    {id:'system',code:'04',title:'연결 단계 · 구간별 모델을 실제 20 m 링크에 붙이기',short:'20 m 전체에 연결',scene:'room',kind:'system',
      plain:'첫 확장은 01·02의 케이블 모델을 20 m 조건으로 가져가는 것입니다. 이어 실제 분기·상용 랜선·커넥터·PCB·T2·양끝 부하와 주변 반환 경로까지 붙여 실제 링크 조건을 만듭니다.',
      route:'케이블 모델 + PCB 모델 + T2·양끝 부하 + 20 m·분기·상용 랜선·환경 → 실제 구성의 양끝 응답',
      example:'예를 들어 짧은 케이블에서 전원쌍 변경이 유리했다면, 실제 20 m와 연결부·장치 부하를 넣어도 그 이점이 유지되는지 확인합니다. 방 전체를 이 3D 그대로 한 번에 계산한다는 뜻은 아닙니다.',
      question:'국부 시험의 차이가 현재의 20 m 링크에서도 의미가 있는가?',
      input:'측정하거나 범위로 가정한 전원/공통모드 자극, 실제 PHY 신호와 소스·부하 임피던스. 자극이 가정이면 그 상태를 결과에 유지합니다.',
      reference:'SMPS 0 V, FG/외함, 철제 테이블, 센서 함체, PC 기준을 구분합니다. 확인되지 않은 접촉은 단락과 개방으로 임의 확정하지 않습니다.',
      probe:'PC와 LAN9354 양끝의 Vd/Vcm 및 전원. 별도 회로/측정으로 PHY 전원·RESET·25 MHz 클록 상태와 오류 로그를 함께 확인합니다.',
      compare:'짧은 openEMS 모델의 검증된 다중포트/분포정수와 별도 다도체 전송선·회로 모델을 연결합니다. 먼저 두 길이에서 연결 방법을 검증합니다.',
      included:'20 m 복합 케이블, SMPS 근처의 짧은 전원 분기, PC까지 긴 상용 랜선, 양끝 부하 및 환경의 반환 경로.',
      excluded:'짧은 시험편 전달전압을 길이 비율로 곱하는 계산. 코일 턴 사이 결합을 무시한 직선 모델로 감긴 20 m 전체를 검증했다는 판단.',
      decision:'의심 경로가 충분한 크기의 수신/전원 변동을 만들 수 있는지 확인한 뒤, 그 변수 하나를 바꾸는 실물 A/B 시험과 동기 로그로 확인합니다.',
      limitation:'openEMS는 LAN9354의 등화·클록 복구·펌웨어·드라이버 전체 모델이 아닙니다. 현재 자료로 3일 뒤 오류의 발생 시각이나 확률을 계산하지 않습니다.',
      metrics:[['양끝 수신 파형 / 전원 변동','자극·부하·대역 근거 포함'],['코일·접촉·길이 민감도','환경 모델 / 실측 확인'],['실물 A/B 및 동기 로그','같은 시간창의 PHY·PC·전원']],
      sources:['setup','solver','emc','phy'],next:null}
  ]
};
