'use strict';
const $=id=>document.getElementById(id),inflate=(s,T=Float32Array)=>{const a=s instanceof Uint8Array?s:pako.inflate(Uint8Array.from(atob(s),c=>c.charCodeAt(0)));return new T(a.buffer,a.byteOffset,a.byteLength/T.BYTES_PER_ELEMENT);};
const state={log:4,frame:22,view:'whole',loaded:null,token:0};let syncing=false;
const rad=a=>a*Math.PI/180,rotate=(p,a)=>[p[0],Math.cos(rad(a))*p[1]-Math.sin(rad(a))*p[2],Math.sin(rad(a))*p[1]+Math.cos(rad(a))*p[2]];
function angle(which){if($('pose').value==='native'){if(which==='core')return FULLSHAPE.native[state.log]?.[state.frame]??FULLSHAPE.angles[state.log].core;return DATA.logs.find(x=>x.id===state.log).frames[state.frame].modes[1].pose[1];}return FULLSHAPE.angles[state.log][which];}
const views=['left','right'].map((id,i)=>{const scene=new THREE.Scene();scene.background=new THREE.Color(0x080e16);const camera=new THREE.PerspectiveCamera(40,1,.03,1500);camera.up.set(0,0,1);const renderer=new THREE.WebGLRenderer({canvas:$(id),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));const controls=new THREE.OrbitControls(camera,renderer.domElement);controls.screenSpacePanning=true;controls.minDistance=.7;controls.maxDistance=600;const model=new THREE.Group(),cloud=new THREE.Group();scene.add(model,cloud,new THREE.HemisphereLight(0xd6edff,0x34465a,1.1));const light=new THREE.DirectionalLight(0xffffff,.8);light.position.set(60,30,100);scene.add(light);
const parts=MODELS.map((m,j)=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(inflate(m.vertices),3));g.setIndex(new THREE.BufferAttribute(inflate(m.indices,Uint32Array),1));g.computeVertexNormals();const group=new THREE.Group();group.add(new THREE.Mesh(g,new THREE.MeshPhongMaterial({color:[0xb5c5d0,0x99bace,0x829baa][j],transparent:true,opacity:.28,side:THREE.DoubleSide,depthWrite:false})),new THREE.LineSegments(new THREE.EdgesGeometry(g,32),new THREE.LineBasicMaterial({color:0xc4d2dd,transparent:true,opacity:.50})));model.add(group);return group;});return {scene,camera,renderer,controls,model,cloud,parts,key:i?'core':'before'};});
views.forEach((v,i)=>v.controls.addEventListener('change',()=>{if(syncing)return;syncing=true;const other=views[1-i];other.camera.position.copy(v.camera.position);other.camera.quaternion.copy(v.camera.quaternion);other.camera.zoom=v.camera.zoom;other.controls.target.copy(v.controls.target);other.camera.updateProjectionMatrix();other.controls.update();syncing=false;}));
function clear(g){while(g.children.length){const c=g.children[0];g.remove(c);c.geometry.dispose();c.material.dispose();}}
function resize(){for(const v of views){const el=v.renderer.domElement,w=el.clientWidth,h=el.clientHeight;v.renderer.setSize(w,h,false);v.camera.aspect=w/h;v.camera.updateProjectionMatrix();}}
new ResizeObserver(resize).observe(document.querySelector('.panels'));window.addEventListener('resize',resize);
function setView(name){state.view=name;let target,dist;
 if(name==='whole'){views.forEach(v=>v.scene.updateMatrixWorld(true));const box=new THREE.Box3();views.forEach(v=>box.union(new THREE.Box3().setFromObject(v.model)));target=box.getCenter(new THREE.Vector3());const size=box.getSize(new THREE.Vector3());dist=Math.max(size.z,size.y,size.x)/2/Math.tan(rad(20))*1.22;}else{const centers={cabin:[2,1,-.6],rear:[0,-5,4.5],center:[0,-1.5,4],jib:rotate([0,18,1],angle('core')),tower:[0,-.38,-13]};target=new THREE.Vector3(...centers[name]);dist={cabin:12,rear:27,center:19,jib:30,tower:43}[name];}
 const dir=new THREE.Vector3(1,-.6,.20).normalize();syncing=true;for(const v of views){v.controls.target.copy(target);v.camera.position.copy(target).addScaledVector(dir,dist);v.controls.update();}syncing=false;}
function inside(p,b){return p[0]>=b[0]&&p[0]<=b[1]&&p[1]>=b[2]&&p[1]<=b[3]&&p[2]>=b[4]&&p[2]<=b[5];}
function transform(p,m){return m.slice(0,3).map(r=>r[0]*p[0]+r[1]*p[1]+r[2]*p[2]+r[3]);}
function build(){if(!state.loaded)return;let n=0;for(const v of views){clear(v.cloud);v.parts[1].rotation.x=rad(angle(v.key));let count=0;
 for(let s=0;s<2;s++){if(!$('s'+s).checked)continue;const a=state.loaded['p'+s],out=[],m=FULLSHAPE.transforms[v.key][s],oldM=FULLSHAPE.transforms.old[s];for(let i=0;i<a.length;i+=3){const p=[a[i],a[i+1],a[i+2]],q=transform(p,oldM),j=rotate(p,-FULLSHAPE.angles[state.log].before);if(!$('all').checked&&!inside(q,[-4,4,-9,3,-3.5,12.5])&&!inside(q,[-3,3,-3.4,2.7,-24,-3])&&!inside(j,[-3,3,3,58,-3,5]))continue;out.push(...transform(p,m));}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(out),3));v.cloud.add(new THREE.Points(g,new THREE.PointsMaterial({color:s?0x69dcb0:0xff8d79,size:2,sizeAttenuation:false,transparent:true,opacity:.86})));count+=out.length/3;}
 v.cloud.visible=$('cloud').checked;n=count;$(v.key==='core'?'rightCaption':'leftCaption').textContent=`JIB ${angle(v.key).toFixed(3)}° · ${$('pose').value==='native'?'실행파일 출력':'별도 정합 각도'}`;}
 $('count').textContent=`양쪽 동일한 ${n.toLocaleString()}점 · 로그 ${state.log} / 묶음 ${state.frame}`;$('frameNo').textContent=state.frame;$('notice').textContent=$('pose').value==='native'?'동일한 버스트 필터 ON 조건의 기존 실행파일 출력을 비교합니다. EXE·모델 수정은 없습니다.':'지브 각도는 캘리브레이션마다 별도로 정합한 값입니다. 이 각도는 JSON에 넣지 않았습니다.';
 const names={cabin_roof:'운전실 위쪽',cabin_sides:'운전실 옆면',rear_upper:'뒤쪽 몸체',center_support:'몸체 중앙',jib_near:'지브 가까운 부분',jib_mid:'지브 중간',tower_upper:'타워 위쪽',tower_middle:'타워 중간'};let html='';for(const [name,label]of Object.entries(names))for(const s of [1,2]){const r=FULLSHAPE.metrics.filter(x=>x.dataset===`0908_log${state.log}`&&x.sensor===s&&x.region===name),a=r.find(x=>x.calibration==='before'),b=r.find(x=>x.calibration==='core');if(a&&b)html+=`<tr><td>${label}</td><td>${s}</td><td>${a.median.toFixed(3)} m</td><td>${b.median.toFixed(3)} m</td></tr>`;}$('stats').innerHTML=html;window.calibrationReady={log:state.log,frame:state.frame,points:n,angles:views.map(v=>angle(v.key))};}
window.registerFrame=(key,d)=>{if(key!==`l${state.log}f${state.frame}`)return;state.loaded={p0:inflate(d.raw0),p1:inflate(d.raw1)};build();};
function load(){
 state.loaded=null;const token=++state.token,key=`l${state.log}f${state.frame}`;
 $('notice').textContent='점군을 불러오는 중…';
 loadPackedFrame(`data/${key}.bin`).then(data=>{if(token===state.token)window.registerFrame(key,data);})
 .catch(error=>{if(token===state.token)$('notice').textContent=error.message;});
}
$('log').onchange=()=>{state.log=+$('log').value;load();};$('frame').oninput=()=>{state.frame=+$('frame').value;$('frameNo').textContent=state.frame;load();};$('pose').onchange=build;for(const id of ['s0','s1','cloud','all'])$(id).onchange=build;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
resize();views.forEach(v=>v.parts[1].rotation.x=rad(angle(v.key)));setView('whole');load();function tick(){requestAnimationFrame(tick);for(const v of views)v.renderer.render(v.scene,v.camera);}tick();
