const puppeteer=require('puppeteer'),fs=require('fs'),path=require('path'),assert=require('assert');
const origin=(process.env.ATLAS_ORIGIN||'http://127.0.0.1:8000').replace(/\/$/,'')+'/';
const out=path.resolve(__dirname,'../reports/porta-test-plan'),qa=path.join(require('os').tmpdir(),'atlas-porta-test-qa');fs.mkdirSync(qa,{recursive:true});
(async()=>{
 const browser=await puppeteer.launch({headless:true,args:['--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});const page=await browser.newPage();await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await page.setViewport({width:1500,height:1100,deviceScaleFactor:1});
 const errors=[],bad=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)bad.push([r.status(),r.url()]);});
 const state=()=>page.evaluate(()=>__trialScene.snapshot());
 const shot=async(name,selector='.workbench')=>{await page.$eval(selector,e=>e.scrollIntoView({block:'center',behavior:'instant'}));await new Promise(r=>setTimeout(r,300));await (await page.$(selector)).screenshot({path:path.join(qa,name+'.png')});};
 try{
  await page.goto(origin+'reports/porta-test-plan/',{waitUntil:'networkidle0'});await page.waitForFunction(()=>window.__testPlan?.ready&&window.__trialScene?.ready);assert.equal((await state()).caseId,'power');assert.deepEqual((await state()).powerPairs,[['+','+'],['0','0']]);assert.equal((await state()).wireCount,8);
  await shot('power');await (await page.$('#coupon-panel')).screenshot({path:path.join(out,'cover.png')});
  assert.equal((await state()).markers.filter(p=>p.role==='probe').length,2);assert.equal((await state()).shieldPresentInPlan,true);await page.click('[data-point="probe-a"]');assert.equal((await state()).role,'probe-a');const camA=(await state()).camera;await page.click('[data-point="probe-b"]');assert.equal((await state()).role,'probe-b');assert.notDeepEqual((await state()).camera,camA);await page.click('.roles [data-role="all"]');
  await page.click('#paired');assert.deepEqual((await state()).powerPairs,[['+','0'],['+','0']]);await shot('paired','#coupon-panel');
  await page.click('.roles [data-role="source"]');assert.equal((await state()).role,'source');await shot('source','#coupon-panel');await page.click('.roles [data-role="probe"]');await shot('probe','#coupon-panel');await page.click('.roles [data-role="all"]');
  await page.select('#shield','both');assert.equal((await state()).bondCount,2);await page.click('#show-shield');assert.equal((await state()).shieldVisible,false);assert.equal((await state()).shieldPresentInPlan,true);assert.equal((await state()).bondCount,2);await page.click('#show-shield');await page.click('[data-point="shield"]');assert.equal((await state()).role,'shield');await shot('shield-close','#coupon-panel');await page.click('.roles [data-role="all"]');await page.click('#show-grid');assert.equal((await state()).gridVisible,true);await page.click('#show-grid');
  for(const [id,value]of[['length','300'],['height','35'],['pitch','30']])await page.$eval('#'+id,(e,value)=>{e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));},value);assert.equal((await state()).params.length,300);
  await page.$eval('#cm-cap',e=>{let p=e;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}});await page.select('#cm-cap','10');assert.equal((await state()).params.cmCap,10);
  await page.click('#test-tabs [data-test="common"]');assert.equal((await state()).params.length,120);assert.equal((await state()).bondCount,0);assert.equal(await page.evaluate(()=>__testPlan.currentConfig.external_RF_source),false);assert((await page.$eval('#case-example',e=>e.textContent)).includes('25 V / 1 V'));assert.deepEqual((await state()).markers.filter(p=>p.role==='source').map(p=>p.id),['source-plus','source-zero']);await page.click('.roles [data-role="source"]');await shot('common-source-attached','#coupon-panel');await page.click('.roles [data-role="all"]');await page.select('#shield','near');assert.equal((await state()).bondCount,1);await shot('common');
  await page.click('#test-tabs [data-test="check"]');assert.equal((await state()).kind,'reference');await shot('reference');await page.click('#stub');assert.equal((await state()).stub,false);await page.click('#stub');
  await page.click('#test-tabs [data-test="pcb"]');await page.waitForFunction(()=>window.__pcbViewer?.ready,{timeout:50000});assert.equal((await page.evaluate(()=>__pcbViewer.snapshot())).planMarkers[0].ref,'CON1');assert.equal(await page.evaluate(()=>__testPlan.currentConfig.transformer.designPart),'HX1260FNLT');assert.equal(await page.evaluate(()=>__testPlan.currentConfig.transformer.internalModelObtained),false);await shot('pcb-cable');
  await page.click('#segment-phy');await page.click('[data-pair="tx"]');const pcb=await page.evaluate(()=>__pcbViewer.snapshot());assert.equal(pcb.segment,'phy');assert.equal(pcb.planMarkers[1].ref,'U6');assert(pcb.planMarkers.every(m=>m.pads.every(p=>p.net.startsWith('TXA'))));await page.click('.roles [data-role="probe"]');assert((await page.$eval('#point-detail',e=>e.textContent)).includes('U6'));await shot('pcb-phy-probe');await page.click('.roles [data-role="reference"]');assert.equal((await page.evaluate(()=>__pcbViewer.snapshot())).inner,true);
  await page.click('#test-tabs [data-test="system"]');await page.waitForFunction(()=>window.__labRoom?.ready,{timeout:50000});assert.equal((await page.evaluate(()=>__labRoom.snapshot())).breakoutNearSmps,true);await shot('room');await page.click('[data-room="breakout"]');await shot('breakout','#room-wrap');await page.click('.roles [data-role="source"]');await shot('room-source','#room-wrap');
  await page.click('#test-tabs [data-test="power"]');await page.focus('#experiment-scene');const before=(await state()).camera;await page.keyboard.press('ArrowLeft');assert.notDeepEqual((await state()).camera,before);await page.keyboard.press('Home');
  assert.equal(await page.evaluate(()=>__testPlan.currentConfig.solver_run),false);assert.deepEqual(await page.evaluate(()=>__testPlan.currentConfig.results),[]);assert.equal(await page.$$eval('.metric .empty',es=>es.every(e=>e.textContent==='—')),true);
  await page.evaluate(()=>{const original=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(this.download&&this.href.startsWith('blob:')){window.__exportName=this.download;window.__exportData=fetch(this.href).then(r=>r.json());}return original.call(this);};});await page.click('#export-plan');const exported=await page.evaluate(()=>window.__exportData);assert.equal(await page.evaluate(()=>window.__exportName),'porta-power-proposed.json');assert.equal(exported.solver_run,false);assert.deepEqual(exported.results,[]);
  await page.setViewport({width:390,height:844});await page.reload({waitUntil:'networkidle0'});await page.waitForFunction(()=>window.__trialScene?.ready);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile horizontal overflow');await page.screenshot({path:path.join(qa,'mobile-top.png')});await shot('mobile-power','#coupon-panel');
  for(const id of ['check','common','pcb','system']){await page.click('#test-tabs [data-test="'+id+'"]');if(id==='pcb')await page.waitForFunction(()=>window.__pcbViewer?.ready,{timeout:50000});if(id==='system')await page.waitForFunction(()=>window.__labRoom?.ready,{timeout:50000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow in '+id);await shot('mobile-'+id,id==='pcb'?'#pcb-panel':id==='system'?'#room-panel':'#coupon-panel');}
  const clipped=await page.evaluate(()=>{const wrap=document.getElementById('room-wrap').getBoundingClientRect();return [...document.querySelectorAll('#room-labels span')].filter(e=>!e.hidden).filter(e=>{const r=e.getBoundingClientRect();return r.left<wrap.left-1||r.right>wrap.right+1;}).map(e=>e.textContent);});assert.deepEqual(clipped,[]);
  await page.goto(origin,{waitUntil:'networkidle0'});await page.waitForSelector('a[href="reports/porta-test-plan/"]');await Promise.all([page.waitForNavigation({waitUntil:'networkidle0'}),page.click('a[href="reports/porta-test-plan/"]')]);assert(page.url().includes('/porta-test-plan/'));await Promise.all([page.waitForNavigation({waitUntil:'networkidle0'}),page.click('.topbar>a')]);assert.equal(page.url(),origin);
  await page.goto(origin+'reports/porta-lab-setup/',{waitUntil:'networkidle0'});await page.waitForSelector('a[href="../porta-test-plan/"]');await Promise.all([page.waitForNavigation({waitUntil:'networkidle0'}),page.click('a[href="../porta-test-plan/"]')]);assert(page.url().includes('/porta-test-plan/'));await Promise.all([page.waitForNavigation({waitUntil:'networkidle0'}),page.click('.topbar nav a[href="../porta-lab-setup/"]')]);assert(page.url().includes('/porta-lab-setup/'));
  console.log(JSON.stringify({pageErrors:errors,badResponses:bad,checked:'5 cases, power assignments, shield topology, dimensions, CM loads, stub, pad markers, lazy room/PCB, focus, keyboard, mobile, export, landing and lab navigation',qa}));assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);
  fs.writeFileSync(path.join(qa,'verification.json'),JSON.stringify({pageErrors:errors,badResponses:bad,solverRun:false,interactiveChecks:'passed'},null,2));
 }catch(e){console.error(e,{errors,bad});await page.screenshot({path:path.join(qa,'failure.png')});process.exitCode=1;}finally{await browser.close();}
})();
