const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'reports/porta-lab-setup');
const setup=vm.runInNewContext(fs.readFileSync(path.join(out,'setup-data.js'),'utf8')+'\nSETUP');
const nodes=setup.nodes.map(({x,y,w,h,...n})=>n);
const edges=setup.edges.map(({d,lx,ly,...e})=>e);
const inputs={schema_version:1,revision:setup.revision,review_required:true,user_approved:false,simulation_run:false,
  units:{length:'mm',voltage:'V',frequency:'Hz'},purpose:'Review this experimental topology before defining and running openEMS models.',
  operating_observation:{source:'user conversation',elapsed_normal_operation:'approximately 3 days',event:'intermittent Ethernet interruption / symbol or CRC error reported; exact event sequence unknown',sensor:'motor and LiDAR rotating'},
  confirmed:{mains_voltage_v:220,two_different_outlets_same_room:true,pc_and_monitor_same_power_strip:true,monitor_link:'HDMI',mouse_keyboard_shared_wireless_dongle:true,sensor_psu_output_v:24,ethernet_cable_length_mm:{nominal:20000,approximate:true},ethernet_conductors_reported:4,cable_placement:'coiled on room floor',coupler:'passive RJ45 female-to-female',patch_cable_length_mm:null,cable_total_conductors:8,cable_contains_dc_power:true,twisted_pairs:[['Ethernet pair 1 conductor A','Ethernet pair 1 conductor B'],['Ethernet pair 2 conductor A','Ethernet pair 2 conductor B'],['+24 V','+24 V'],['0 V','0 V']],pair_identity_is_pinmap:false,shield_present:true,shield_description:'braid (user description)',shield_end_bonds:{pc_end:false,sensor_end:false},breakout_location:'near SMPS at the non-sensor end of the 20 m cable',breakout_to_psu_relative_length:'short',commercial_ethernet_to_pc_relative_length:'long',sensor_connection:'one M12 8-pin',sensor_support:'steel test table shared with SMPS',devices_placed_directly_on_steel_surface:true,sensor_surface:'anodized',deliberate_table_bond_wire:false,psu_model:'MEAN WELL LRS-350-24',psu_mains_terminals_connected:['L','N','FG (PE)']},
  unresolved_physical_values:{cable_part_number:null,shield_material:null,shield_coverage:null,shield_dimensions_mm:null,twist_pitch_mm:null,pair_mapping:null,conductor_diameter_mm:null,cable_dielectric:null,psu_output_0v_to_fg_extra_bond:null,psu_to_table_contact_impedance:null,sensor_to_table_contact_impedance:null,breakout_to_psu_length_mm:null,breakout_to_rj45_length_mm:null,pc_model:null,pc_phy_model:null,t2_model:null,earth_connections:null,dc_return_to_chassis:null,table_dimensions_mm:null,room_dimensions_mm:null,coil_diameter_mm:null,coil_turns:null},
  illustration_geometry:{is_solver_mesh:false,room_coordinates_are_display_only:true,sensor_mechanics:'ATLAS PPT-based approximation',pcb:'Gerber signal and ground display geometry; source/mesh audit needed',board_component_xy:'KiCad-derived display data',component_heights:'approximate',cable_curve_is_not_physical_input:true},
  known_legacy_discrepancies:['Previous ATLAS assembly assumes a cabinet and Ethernet+24V composite cable; current lab setup has two outlets, a desktop PC/monitor, passive coupler. DC power shares the Ethernet cable as confirmed on 2026-09-13; no cabinet is assumed.','155 mm assembly width vs approximately 150 mm housing-joint radius in EMC narrative require identification of the actual feature and units.','PCB display and mechanical assembly use different coordinate conventions; transforms must be audited before solving.'],
  manufacturer_reference:{source:setup.sources.meanwell.href,dimensions_mm:[215,115,30],rated_output_v:24,rated_current_a:14.6,fg_to_chassis_continuity_documented:true,fg_to_chassis_source:setup.sources.meanwelltest.href,not_a_measurement_of_this_unit:true,no_noise_waveform_derived_from_nameplate:true},
  proposed_observables:['LAN9354 PortA receiver differential and common-mode voltage','PC receiver differential and common-mode voltage','PHY supply relative to local ground','RBIAS / RESET / reference clock disturbance when supported by circuit model'],
  simulation_boundaries:{no_crc_failure_prediction_without_receiver_model:true,do_not_short_unconfirmed_ground_nodes:true,do_not_treat_display_scene_as_fdtd_mesh:true,no_invented_results:true},nodes,edges,sources:setup.sources,questions:setup.unknowns};
fs.writeFileSync(path.join(out,'data/model-inputs.json'),JSON.stringify(inputs,null,2)+'\n');
const prov=JSON.parse(fs.readFileSync(path.join(out,'data/provenance.json'),'utf8')).filter(p=>p.copy!=='data/sensor-construction.js');
for(const p of prov){if(p.copy==='viewer.js'){p.source_sha256=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p.source))).digest('hex');p.sha256=crypto.createHash('sha256').update(fs.readFileSync(path.join(out,p.copy))).digest('hex');p.adaptation='Keyboard rotation/zoom added; original display geometry and selection behavior preserved.';}}
prov.push({source:'reports/porta-pcb/assembly.html',copy:'data/sensor-construction.js',sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(out,'data/sensor-construction.js'))).digest('hex'),adaptation:'Extracted sensor construction only; removed prior external cabinet/cable illustration. Mechanical assumptions retained and disclosed.'});
for(const p of prov){p.sha256=crypto.createHash('sha256').update(fs.readFileSync(path.join(out,p.copy))).digest('hex');p.source_sha256=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p.source))).digest('hex');}
fs.writeFileSync(path.join(out,'data/provenance.json'),JSON.stringify(prov,null,2)+'\n');
const catalogPath=path.join(root,'reports.json'),catalog=JSON.parse(fs.readFileSync(catalogPath,'utf8'));
const entry={id:'porta-lab-setup',title:'PALA720 · PortA 실험실 구성 확인',summary:'두 콘센트, PC·모니터, SMPS, 8선 복합 케이블·양끝 미접속 실드·철제 테이블. 전원·통신·접지 후보를 연결 지도와 실제 PCB·센서 3D로 대조합니다.',category:'EMC · 구성 검토',collection:'emc',date:'2026-09-13',path:'reports/porta-lab-setup/',cover:'reports/porta-lab-setup/cover.png',coverAlt:'실험실 연결 지도. PC와 센서의 별도 전원, 수동 RJ45 커플러와 20 m 케이블, 센서 내부 LAN9354 경로를 표시합니다.',tags:['구성 확인','전원·접지','3D','openEMS 준비']};
const idx=catalog.reports.findIndex(r=>r.id===entry.id);if(idx>=0)catalog.reports[idx]=entry;else catalog.reports.splice(catalog.reports.findIndex(r=>r.id==='emc-design')+1,0,entry);
fs.writeFileSync(catalogPath,JSON.stringify(catalog,null,2)+'\n');
console.log('Registered one report; exported physical inputs without illustration coordinates.');
