// Keep plan evidence portable; model snapshots are not solver-ready geometry.
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'reports/porta-test-plan');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const b={};vm.runInNewContext(fs.readFileSync(path.join(dir,'data/board-components.js'),'utf8')+';this.data=BOARD_COMPONENTS',b);
function point(board,ref,nets){const part=b.data[board].parts.find(p=>p.ref===ref);const pads=part.pads.filter(p=>nets.includes(p.net));if(pads.length!==2)throw Error(`${board} ${ref}: expected two pads for ${nets}`);return {board,ref,pads:pads.map(p=>({pin:p.n,net:p.net,xy:p.xy})),xy:[pads.reduce((s,p)=>s+p.xy[0],0)/2,-pads.reduce((s,p)=>s+p.xy[1],0)/2]};}
const points={};for(const segment of ['cable','phy']){points[segment]={};for(const pair of ['rx','tx']){const net=pair.toUpperCase();points[segment][pair]=segment==='cable'?{source:point('Motor_board','CON1',[`Eth_${net}+`,`Eth_${net}-`]),probe:point('Control_board','T2',[`Eth_${net}+`,`Eth_${net}-`])}:{source:point('Control_board','T2',[`${net}A+`,`${net}A-`]),probe:point('Control_board','U6',[`${net}A+`,`${net}A-`])};}}
fs.writeFileSync(path.join(dir,'data/pcb-points.js'),'const PCB_PLAN_POINTS = '+JSON.stringify(points)+';\n');
const t={};vm.runInNewContext(fs.readFileSync(path.join(dir,'cases.js'),'utf8')+';this.data=TEST_PLAN',t);
const recheck=JSON.parse(fs.readFileSync(path.join(root,'reports/porta-pcb/records/tx-recheck/summary.json'),'utf8'));
const phy=JSON.parse(fs.readFileSync(path.join(root,'reports/porta-pcb/records/phy-initial-summary.json'),'utf8'));
const t2=b.data.Control_board.parts.find(p=>p.ref==='T2');
const audit={date:'2026-09-13',newSolverRun:false,transformer:{designPart:'HX1260FNLT',designEvidence:'ATLAS assessment names HX1260FNLT; copied KiCad footprint '+t2.fp,asBuiltIdentity:'not separately verified on the physical unit',internalModelObtained:false,partIdentityCorrection:'Part identity is documented; the electrical model remains unavailable in the inspected ATLAS records.',phyCenterTapPins:['2','7'],phyCenterTapNet:'VDD33TXRX1_43',cableCenterTapPins:['10','15'],cableCenterTapNets:['Net-(T2-CT_Rx)','Net-(T2-CT_Tx)'],centerTapNote:'KiCad net names are available; their complete mounted load network still needs inclusion.'},cable:{frequencyMHz:recheck.frequency_mhz,ports:recheck.geometry.ports,storedSShape:[1,4,4],storedDataType:'complex128',selected:recheck.selected,validation:recheck.validation,fullyConverged:recheck.fully_converged,limits:recheck.remaining_model_limits,commonModeStatus:'Four differential ports cannot supply the missing common-mode port responses by reformatting this matrix.'},phy:{scope:phy.model_scope,validation:phy.numerical_validation,reuseCheck:'Inspect original conductor-level voltages/currents and excitations before deciding whether mixed-mode responses can be extracted. The published summary alone is not sufficient.'},reuseDecision:'Reuse the Gerber and existing SI evidence; do not repeat the same 100 MHz SI calculation by default. Additional work targets common-mode conversion, T2 and mounted loads, and the frequency range relevant to cable trials.',sources:['reports/porta-pcb/assessment.md','reports/porta-pcb/records/tx-recheck/summary.json','reports/porta-pcb/records/tx-recheck/fine-fem-results.npz','reports/porta-pcb/records/phy-initial-summary.json','reports/porta-test-plan/data/board-components.js'].map(source=>({source,sha256:hash(path.join(root,source))}))};
fs.writeFileSync(path.join(dir,'data/pcb-audit.json'),JSON.stringify(audit,null,2)+'\n');
fs.writeFileSync(path.join(dir,'data/pcb-audit.js'),'const PCB_AUDIT = '+JSON.stringify(audit)+';\n');
const plan={...t.data,status:'proposed_test_plan',geometryStatus:'interactive explanation, not solver mesh',results:[],baselineFile:'lab-baseline.json',baselineCorrectionsFile:'pcb-audit.json',cableEvidenceFile:'cable-spec.json',cableCorrection:'User confirmed Northwire FAWM248-076 / drawing 47674-1 Rev C. Cable dimensions, materials and foil plus braid supersede the unknown fields in the historical lab baseline. Twist pitch and electrical material properties remain unverified.',baselineCorrection:'The historical lab-review-03 snapshot lists T2 part as unknown; the subsequent ATLAS design audit identifies HX1260FNLT. Electrical model remains unverified.',markerSource:'board-components.js, exact pad XY; display averages each pair',completedRunsManifest:'../records/initial-openems/manifest.json',latestReviewManifest:'../records/screening-review-06/manifest.json',resultsScope:'This proposed configuration is unexecuted. The first cable results are retained but their physical interpretation is withdrawn after the PEC connection review.',nextDeliverable:'Recompute using connected meshes; verify power transmission first, then compare dominant Ethernet outputs across record lengths and meshes.'};
fs.writeFileSync(path.join(dir,'data/plan.json'),JSON.stringify(plan,null,2)+'\n');
const prior=JSON.parse(fs.readFileSync(path.join(dir,'data/provenance.json'),'utf8'));
for(const entry of prior){entry.source_sha256=hash(path.join(root,entry.source));entry.copy_sha256=hash(path.join(dir,entry.copy));entry.adapted=entry.source_sha256!==entry.copy_sha256;delete entry.sha256;}
fs.writeFileSync(path.join(dir,'data/provenance.json'),JSON.stringify(prior,null,2)+'\n');
console.log('Prepared test plan data and pad coordinates; no simulation performed.');
